### ISSUE TITLE
[ Feature ] Export arbitrary binary from container & direnv

### ISSUE THREAD

**Issue by FrauH0lle** [89luca89/distrobox#11]
Hello and thank you very much for creating this project!

As far as I understand, `distrobox-export --app` can only export applications which have a `.desktop` file. Would it be possible to extend this to programs in `/bin` or `usr/bin`? Or have an option like `distrobox-export --bin` which does that?

Background:

I discovered your project and [dahbox](https://github.com/jecicorp/dahbox) around the same time during the last days when I was searching for a possibility to have project specific environments (and not using the nix package manager or nixos) with [direnv](https://github.com/direnv/direnv).
Both projects have a similar scope but yours seems to be more generic in terms of available container images. That's why I am opening this request.

The workflow I mean is described [here](https://github.com/jecicorp/dahbox#boxes-per-projet), and I would imagine it could look similar to this:

```bash
# Direnv setup
echo "PATH_add $PWD/.distrobox-bin" > .envrc
direnv allow

# Export from distrobox
# I currently work a lot in R, so I will use it as an example
distrobox-export --bin R --export-to "$PWD/.distrobox-bin"

# This would create a bash script $PWD/.distrobox-bin/R which would point to R in the container which in turn would be added to $PATH via direnv when the user works in this project folder.
```

Would this be feasible for this project or is it out of scope?

**Comment by 89luca89** [comment]
Hello, and thank you for taking some time to open this issue!

I see no problems with including a `--bin/-b` option to `distrobox-export` if done correctly we could use it as a base for also `--app/-a` and `--service/-s` 

What I would like to find, is a way to make it a bit more seamless with the host
I mean without having to fiddle with `direnv` or rc files in general

On one hand `direnv` easily solves the problem of having multiple versions of the same `bin` exported 
On the other hand having to manage direnvs and rc files is not an easy fit to do correctly and safely

Having the `--export-to` flag, would allow you to have this direnv workflow (which I like)

But on the other hand, I would like to have a way (or a sane default) so that it works without that flag, and exports the bin in the user home's $PATH

The little problem is that $PATH is shared between host and container, so it would create a loop if you launch the exported bin inside the container :smile: 

A quick way would be to add this snippet to a `~/.profile` 

```
	if [ ! -f /run/.containerenv ]; then
            # we are on the host
            PATH=$PATH:$HOME/.distrobox-bin/
         fi
```

this would allow a generic way to export a bin to the whole user path, then you can use the `--export-to` to specify for example various versions of `bin` (for example, one on debian., one on ubuntu etc etc) using then `direnv` for the single project.

---

But I would like to find a way to make this work globally without touching rc files as it introduces a difficulty level both on the safety of touching those files without breaking anything, and on the cleanness side of things (for eg, `podman rm` of a distrobox would leave a lot of non-working bins inside this folder)

Any ideas?

**Comment by 89luca89** [comment]
> I see no problems with including a `--bin/-b` option to `distrobox-export` if done correctly we could use it as a base for also `--app/-a` and `--service/-s`

I would like to expand on this
creating an `export_bin` function, it could be used when we export an app or a service

at that point the service or the app becomes much easier to export, we do not need to fiddle with grep/sed as much (to insert the `distrobox-enter` command) and in general it would simplify the structure of the `distrobox-export` script :+1:

**Comment by FrauH0lle** [comment]
Glad that this request got positive feedback from your side. 

> The little problem is that $PATH is shared between host and container, so it would create a loop if you launch the exported bin inside the container

Indeed, that can be a problem. One solution I could see is to have `distrobox-export --bin` create a wrapper, e.g. `distrobox-export --bin mybinary` creates the file `/home/$USER/.local/bin/mybinary` containing

```bash
if [ ! -f /run/.containerenv ]; then
    # we are on the host
    distrobox-enter --name mycontainer -e /usr/bin/mybinary
else
    echo "Cannot launch within container! Use absolute path usr/bin/mybinary if you need to run it in the container."
fi
```
Maybe have an option like `--bin-path` where the user can specifiy the exact path to the binary in the container .e.g `/opt/mybinary`.

> the problem of having multiple versions of the same bin exported
Maybe a similar solution as Arch does with different [Java versions](https://wiki.archlinux.org/title/java#Switching_between_JVM) [(source)](https://github.com/archlinux/svntogit-packages/blob/packages/java-common/trunk/bin_archlinux-java).
So there could be a folder `/home/$USER/.local/distrobox-bin` containing

```
binA/
 | -- binA-suffix1
 | -- binA-suffix2
 | -- binA-suffix3
```

and the user could run `distrobox-select-bin` which will symlink the chosen suffix to `/home/$USER/.local/bin` to have that specific version globally available.
The suffix could be the container name, as I would expect to have one container per version. 

> cleanness side of things (for eg, podman rm of a distrobox would leave a lot of non-working bins inside this folder)

The could be cleanup script which checks if the cotainer of the bin still exists and if not, offers to remove the script in `distrobox-bin` and symlinks pointing to that file.

Another thought from my side regarding direnv:

If the above approach would exist, I would prefer to have a direnv option or switch. I could use the `.envrc` file to point to the specific binary in `/home/$USER/.local/distrobox-bin`, however I would prefer to everything related to the project I am working on being in that project's directory. Otherwise I need to keep an eye on the global distrobox-managed programs plus the ones in the project directory.

**Comment by 89luca89** [comment]
> Indeed, that can be a problem. One solution I could see is to have `distrobox-export --bin` create a wrapper, e.g. `distrobox-export --bin mybinary` creates the file `/home/$USER/.local/bin/mybinary` containing

Oh yea right, even better we could do

```sh
if [ ! -f /run/.containerenv ]; then
    # we are on the host
    distrobox-enter --name mycontainer -e /usr/bin/mybinary
else
     /usr/bin/mybinary 
fi
```

So it will be transparent if launched inside or outside with the common $PATH :smile: 

> Maybe have an option like --bin-path where the user can specifiy the exact path to the binary in the container .e.g /opt/mybinary.

Do you mean for the source or for the destination?



> Maybe a similar solution as Arch does with different [Java versions](https://wiki.archlinux.org/title/java#Switching_between_JVM) [(source)](https://github.com/archlinux/svntogit-packages/blob/packages/java-common/trunk/bin_archlinux-java). So there could be a folder `/home/$USER/.local/distrobox-bin` containing
> 
> ```
> binA/
>  | -- binA-suffix1
>  | -- binA-suffix2
>  | -- binA-suffix3
> ```
> 
> and the user could run `distrobox-select-bin` which will symlink the chosen suffix to `/home/$USER/.local/bin` to have that specific version globally available. The suffix could be the container name, as I would expect to have one container per version.

That's interesting I woud like to think on this but I don't want to create something too complicated to use maybe we could do something similar with `direnv` so you can have your multi-version binary per-project more easily?

> There could be cleanup script which checks if the cotainer of the bin still exists and if not, offers to remove the script in distrobox-bin and symlinks pointing to that file.

Yea I'm starting to think a `distrobox-destroy` should be added to handle this situations

> If the above approach would exist, I would prefer to have a direnv option or switch. I could use the .envrc file to point to the specific binary in /home/$USER/.local/distrobox-bin, however I would prefer to everything related to the project I am working on being in that project's directory. Otherwise I need to keep an eye on the global distrobox-managed programs plus the ones in the project directory.

Yea I think I'd prefer multi-version to be handled locally in this way more than globally, and globally only leave the bin you directly select as global

---

Was thinking then something like:

- `--bin /usr/bin/mybinary` 
- `--export-path /path/where/to/export` - and default this to something like $HOME/.local/bin for global scope, here you can set your own path of choiche (for version and/or distro) and then use `direnv` in projects to use the specific versions
- `--clean-up` this could be a solution to look for exports in an `--export-path` folder, and check for non-existent containers

When this is done I'd like to use this very implementation of `--bin` to export also `--app` and `--service` so that we will not have to fiddle with desktop and service file paths too much

Sounds good?

**Comment by FrauH0lle** [comment]
> Oh yea right, even better we could do
.....
So it will be transparent if launched inside or outside with the common $PATH smile

Yep, that is better. I would just add a small warning when running in the container, thus the user is made aware of this (for example you have too many terminals open and use the wrong one to launch the command). 

One thing I would like to add:

- The wrapper should include `"$@"` to pass arguments to the command

> >Maybe have an option like --bin-path where the user can specifiy the exact path to the binary in the container .e.g /opt/mybinary.

> Do you mean for the source or for the destination?

I mean for the source. I assumed that the `--bin` would work similar like the `--app` option and would try to find the binary in the `/usr/bin` directory. However, it could be that the user installed the program in the container in a different path and thus, needs to specify it.

> Sounds good?

Absolutely! At least for me, this would cover my use case. 

I agree with you that the multi-versioning idea is interesting but deserves more thought and is a bit out of scope in this issue.

**Comment by 89luca89** [comment]
> The wrapper should include `"$@"` to pass arguments to the command

Yep I was excluding it from the discussion just for clarity but yea will be like this

> I mean for the source. I assumed that the --bin would work similar like the --app option and would try to find the binary in the /usr/bin directory. However, it could be that the user installed the program in the container in a different path and thus, needs to specify it.

I want `--bin` to specify the exact path to the bin so it's easier and more secure to work with

> I agree with you that the multi-versioning idea is interesting but deserves more thought and is a bit out of scope in this issue.

Yep will leave for the future, for now leaving the option to the user to export manually to different paths and then use direnv (or manually setting the PATH) will be enought

**Comment by 89luca89** [comment]
@FrauH0lle I've done a first implementation in the `feature/bin_export` branch

You can replace your `distrobox-export` file with this version:

https://raw.githubusercontent.com/89luca89/distrobox/feature/bin_export/distrobox-export

to try and test it, still not implemented a cleanup function (still deciding if it's in scope or not) 

Let me know how it goes for your `direnv` workflow, it works fine for me using a normal export in one of my $PATH

**Comment by 89luca89** [comment]
@FrauH0lle I've opened a PR for this feature, if you have some time please test if it works as expected, I've played with it and admittedly using it more than expected :smile:  and it's working as intended

Let me know what do you think!

**Comment by 89luca89** [comment]
Hey @FrauH0lle glad it's working well :smile: 

> --export-path seems not to have a default value. I think distrobox-export --bin /usr/bin/vim should export to ~/.local/bin/

I thought of it, but seems like generally speaking ~/.local/bin it's not a canonical path nor it's in default path for users, this could lead to confusing situations like "I exported but it does not work" because they will not know that it's exported there by default and maybe they do not have that directory in path.

> nice addition with the --extra-flags option. I left a comment in the PR, because I think these --extra-flags should also be included in the launch command when inside the container.

Yea that was added in another PR :smile:  anyway I thought the same at the beginning but another point of view (which I personally prefer) is that if I've **exported** in a way, it means I expect it to work said way from the host, and I want the binary (or app) from the inside container to work as expected

For example if I export 

`distrobox-export --bin /usr/bin/vim --extra-flags "-p" --export-path ~/.local/bin`

I expect that exported vim works with `-p` from the host
but inside the container I would want vim to behave normally as the native binary

**Comment by FrauH0lle** [comment]
> I thought of it, but seems like generally speaking ~/.local/bin it's not a canonical path nor it's in default path for users, this could lead to confusing situations like "I exported but it does not work" because they will not know that it's exported there by default and maybe they do not have that directory in path.

Quoting from [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html):
> User-specific executable files may be stored in $HOME/.local/bin. Distributions should ensure this directory shows up in the UNIX $PATH environment variable, at an appropriate place.

But I see your point. `$HOME/local/bin` is not a specifically mentioned in the specifications. However, as far as I know the Debian and Ubuntu families and openSUSE do include `$HOME/.local/bin` in the `$PATH` by default. Probably other distros as well.

> I expect that exported vim works with -p from the host but inside the container I would want vim to behave normally as the native binary

That makes sense. Maybe the description of this option should clarify that `--extra-flags` is intended for options which help the program to run in a container and be called from outside. 

Anyways, all of the above are just my thoughts and in the end you are the boss and you decide :)

**Comment by 89luca89** [comment]
Yea I prefer not to put a default to that folder, I even tried with new users on my ubuntu and they do not have that folder by default, nor it is in PATH.

> Maybe the description of this option should clarify that --extra-flags is intended for options which help the program to run in a container and be called from outside.

Yep I have expanded the various tools help to explain how they work and what they do :smile: 

I'll proceed with the PR then :+1: 
Feel free to resolve this issue if it works as intended for you

**Comment by FrauH0lle** [comment]
> Feel free to resolve this issue if it works as intended for you
It does! Thanks a lot!
