### ISSUE TITLE
[Suggestion] Gentoo guest support

### ISSUE THREAD

**Issue by nullpointerarray** [89luca89/distrobox#112]
**Is your feature request related to a problem? Please describe.**
I would like to use Gentoo in a container but this currently doesn't work.

**Describe the solution you'd like**
It should work like all the other distros.

**Describe alternatives you've considered**
Using it in a container without distrobox works.

**Additional context**
Implemented here: https://github.com/89luca89/distrobox/pull/111#issue-1098091730
To test you need to build your own container. This dockerfile works:
``` 
FROM registry.hub.docker.com/gentoo/portage:latest

FROM registry.hub.docker.com/gentoo/stage3:systemd

COPY --from=portage /var/db/repos/gentoo /var/db/repos/gentoo
```

**Comment by 89luca89** [comment]
Hi @nullpointerarray 
I've left a couple of comments in the PR I see no other problems on that

But from what I understand this won't work with stock `gentoo/stage3` images right? 
Together with the init support we should also craft an addition to the compatibility table so that we can explain what type of image or workaround we need
