### ISSUE TITLE
[Error] Cant create ubuntu container anymore

### ISSUE THREAD

**Issue by biji** [89luca89/distrobox#1146]
**Describe the bug**

Can not create new container using image `docker.io/library/ubuntu:22.04` with these two errors:

```
Creating 'ubuntu-22' using image docker.io/library/ubuntu:22.04	Error: statfs /etc/yum.repos.d/redhat.repo: no such file or directory
 [ ERR ]

...

Creating 'ubuntu-22' using image docker.io/library/ubuntu:22.04	Error: statfs /etc/pki/entitlement: no such file or directory
 [ ERR ]
```

**To Reproduce**

```
distrobox create --image docker.io/library/ubuntu:22.04  --name ubuntu-22 --verbose
```

**Expected behavior**

new container created

**Logs**
Run the commands with `--verbose` and post the log here as a file upload

```
+ cmd='podman --log-level debug create
		--hostname "ubuntu-22.onyx.local"
		--name "ubuntu-22"
		--privileged
		--security-opt label=disable
		--security-opt apparmor=unconfined
		--user root:root
			--ipc host
			--network host
			--pid host
		--label "manager=distrobox"
		--env "SHELL=bash"
		--env "HOME=/home/user"
		--env "container=podman --log-level debug"
		--volume /:/run/host:rslave
		--volume /tmp:/tmp:rslave
		--volume "/usr/bin/distrobox-init":/usr/bin/entrypoint:ro
		--volume "/usr/bin/distrobox-export":/usr/bin/distrobox-export:ro
		--volume "/usr/bin/distrobox-host-exec":/usr/bin/distrobox-host-exec:ro
		--volume "/home/user":"/home/user":rslave
			--volume /dev:/dev:rslave
			--volume /sys:/sys:rslave
			--volume /dev/pts
			--volume /dev/null:/dev/ptmx
			--volume /sys/fs/selinux
			--volume /var/log/journal
			--volume /etc/pki/entitlement/:/run/secrets/etc-pki-entitlement:ro
			--volume /etc/rhsm/:/run/secrets/rhsm:ro
			--volume /etc/yum.repos.d/redhat.repo:/run/secrets/redhat.repo:ro
			--volume /run/user/1000:/run/user/1000:rslave
					--volume /etc/hosts:/etc/hosts:ro
					--volume /etc/resolv.conf:/etc/resolv.conf:ro
			--ulimit host
			--annotation run.oci.keep_original_groups=1
				--userns keep-id
		
	--entrypoint /usr/bin/entrypoint
	docker.io/library/ubuntu:22.04
		--verbose
		--name "user"
		--user 1000
		--group 1000
		--home "/home/user"
		--init "0"
		--nvidia "0"
		--pre-init-hooks ""
		--additional-packages ""
		-- '\'''\''
	'

```

Attach also the output of `podman logs` or `docker logs`, possibly with `--latest` flag

**Desktop (please complete the following information):**
 - Are you using podman, docker or lilipod?

podman

 - Which version or podman, docker or lilipod?

podman version 4.6.2

 - Which version of distrobox?

distrobox: 1.6.0.1

 - Which host distribution?

Fedora release 37

 - How did you install distrobox?
rpm

**Additional context**

**Comment by crakkhead** [comment]
I've encountered the same error on a RHEL 8 machine. AFAICT these lines are the origin of the problem:
https://github.com/89luca89/distrobox/blob/3435f4d27070a99668bfa29a3e508db4ecc09009/distrobox-create#L692-L696
I'm working on a custom setup where there is no /etc/yum.repos.d/redhat.repo file and thus the bind mount fails.

The conditional should include a check if the container is actually a RHEL container or similar, otherwise the bind mounts are not necessary.

I've worked around this for the moment by touching the missing files on the host.

**Comment by noelmiller** [comment]
The bug occurs for me when `subscription-manager` installed on my machine and I am not subscribed through a RHEL subscription due to the bind mount not finding rhel.repo

I think the best way forward on this is to maybe only do this bind mount when using RHEL UBI containers? As that is the only time that it would matter that you have a rhel.repo file. I wouldn't think any other container versions should care about `subscription-manager`.

**Comment by 89luca89** [comment]
Thanks for investigating everyone! I've pushed a fix for this, so that it checks existence before mounting
