### ISSUE TITLE
[Error] Not able to change hostname in init_hooks

### ISSUE THREAD

**Issue by briandipalma** [89luca89/distrobox#1164]
Having a fake hostname causes weird failures when running Java/Hibernate code. I guess Hibernate tries to connect to a DB file using the hostname. The errors that are raised are ClassNotFound ones so it was painful to debug what was going on. Setting the hostname to my local machine one, the correct one, fixes the issue. I've been trying to add it to my init_hooks with no success so far.

```
init-hooks=hostname "$(uname -n)";
```

Causes this

```
brian@brian-pop-os-pc-specialist:~/dev/iac/images$ distrobox assemble create 
/usr/bin/distrobox-assemble: 4: /tmp/tmp.tzoNM46AWF: init-hooks=hostname brian-pop-os-pc-specialist;: not found
```

While

```
"$(uname -n)" > /etc/hostname
```

Causes

```
brian@brian-pop-os-pc-specialist:~/dev/iac/images$ distrobox assemble create 
/usr/bin/distrobox-assemble: 4: /tmp/tmp.7ILlQSqxEf: cannot create /etc/hostname: Permission denied
```

While

```
sudo "$(uname -n)" > /etc/hostname
```

Causes

```
Setting up groups...                    	 [ OK ]
Setting up users...                     	 [ OK ]
Setting up skel...                      	 [ OK ]
Executing init hooks...                 	 Error: An error occurred
```

It would be nice if we could create containers that used their host's hostname as the way I imagine most people use distrobox containers is as local host like environments. I doubt people are deploying them as server host environments.

Something like

`change_hostname=false`

in a distrobox.ini file would be fantastic.

I see the code in `generate_command`, would a PR be accepted?

**Comment by michaelhaaf** [comment]
In the time since making that comment I've come to thinking/realizing a few things:

(1) It's probably that the result of this `init-hook` method creates a new FQDN for the intents and purposes of both resolving to the host name and being unique/individually identifiable on a local network (i.e. there's nothing wrong with `boxname.hostname`). 

It turns out there's already been quite a lot of discussion about this [in this repo](https://github.com/89luca89/distrobox/issues/62) and in [toolbox](https://github.com/containers/toolbox/issues/969) which I only skimmed, but the important parts seem to work (e.g. ssh -x forwarding) in this scheme. 
 
(2) The documentation has a typo, which is a separate issue that I also had run into when trying this out (which is why I knew the fix). I've made a pull request to address this [here](https://github.com/89luca89/distrobox/pull/1182).

(3) OP floated the idea of having a `--hostname` parameter rather thatn using `init-hook` which seems like a reasonable feature, e.g. `docker-compose` has this. There may already be a feature request tracking this if you look.

**Comment by briandipalma** [comment]
1) `boxname.hostname` is the hostname that is set in the container by default. I saw the other issues that talked about hostname setting, that's where I got some of my attempted solutions.

3) The `--hostname` flag is what distrobox uses to tell podman/docker what hostname to set in the container (`boxname.hostname` by default).

In fact I ended up solving the issue using that flag. I replaced the `distrobox.ini` file I was using during the creating of my container with a script that overrides the `--hostname` flag distrobox passes into the container runner.

```bash
distrobox rm env --force;

distrobox create --image docker.io/briandipalma/env:latest \
	--name env \
	--pull \
	--additional-flags "--hostname ${HOSTNAME}" \
	--pre-init-hooks "SHELL=/usr/bin/fish";

distrobox enter env;
```

I'll close the issue as I've a solution that I'm happy with.

**Comment by redbeardymcgee** [comment]
> In fact I ended up solving the issue using that flag. I replaced the `distrobox.ini` file I was using during the creating of my container with a script that overrides the `--hostname` flag distrobox passes into the container runner.

I have `additional_flags="--hostname <sub.domain>"`

I ended up in this issue because I was looking for a way to use command substitution in `init_hooks`. To bootstrap my devbox, I use `sh -c "$(curl -fsLS get.chezmoi.io)" -- -b $HOME/.local/bin`. This fails with the error `tmpdir: parameter not set`.

[This is probably the culprit](https://github.com/89luca89/distrobox/blob/772e86b161a459a804fd579bc54c6c80886bca54/distrobox-create#L443), sort of. I'm not sure how `tmpdir` is unset because [the variable does get set](https://github.com/twpayne/chezmoi/blob/a1196a72c00d5990a4f33433aa8df701b408e4fd/assets/scripts/install.sh#L17).

I thought perhaps it's because `mktemp` might be missing. Try adding `additional_packages=coreutils` or `init_hooks="sudo dnf install -y coreutils"` (or `pre_init_hooks`). Still breaks.

Take the command substitution out.

```ini
init_hooks="curl -sSLf get.chezmoi.io -o chezmoi-installer;"
init_hooks="chmod +x ./chezmoi-installer;"
init_hooks='./chezmoi-installer -b "/home/redbeardymcgee/devbox/.local/bin" init redbeardymcgee --ssh --apply --promptDefaults --force;'
```

`Creating './chezmoi-installer -b " ${init_hooks}' using image registry.fedoraproject.org/fedora-toolbox:latest      /home/josh/.local/bin/distrobox-create: 1: eval: init_hooks: parameter not set`

Huh?
