### ISSUE TITLE
Cannot follow symlinks from distrobox

### ISSUE THREAD

**Issue by biscotty666** [89luca89/distrobox#1176]
Some of the directories in my home directory are symlinks. While I can navigate through the normal directories from within a container, I cannot access the symlinked directories. The links point to directories on an external drive, so perhaps this is the problem. From within a container, it is as if the external drive isn't mounted.  Is there a way to do this?

Thank you

**Comment by HikariKnight** [comment]
This depends on how the symlinks are set up.
Relative symlinks will work as long as the container has access to it within the volume (ex. using a symlink that leads to `../../Folder`, as long as the container can find `Folder` 2 directories up from the symlink it will work)
However if you have a symlink for lets say your `Pictures` folder and it goes to `/mnt/disk1/Pictures`, the container will not have a valid path to `/mnt/disk1/Pictures` as it would be under `/run/host/mnt/disk1/Pictures` inside the container.

I use a bind mount instead of a symlink for when i have things in locations that i want accessible from the home directory but also want accessible through a container, if you have many of these it will look messy in `lsblk` but it is the only way i have found where the container can access the contents that i would otherwise have symlinked.
