### ISSUE TITLE
host-spawn / distrobox-host-exec seems to do nothing with distrobox installed in OpenSUSE MicroOS

### ISSUE THREAD

**Issue by cmspam** [89luca89/distrobox#1198]
Description:
host-spawn and distrobox-host-exec just return nothing when trying to run a process on host.

Steps to Reproduce:
Install microos from kvm image in VM.
Run: transactional-update pkg in distrobox
Launch a new distrobox (tried debian/bookworm as well as tumbleweed)
Enter distrobox, run distrobox-host-exec ls or whatever you like on the host.
There is no result.

I don't really know how to look into this further, but I need this feature unfortunately.
I have tried with both docker and podman backends.

If you have anything I can try, let me know. It is from a fresh installation, no real modifications made, with latest versions of everything as of today.

**Comment by cmspam** [comment]
Update: Actually, same problem exactly with ClearOS as well, using the install sh script to install distrobox.

**Comment by cmspam** [comment]
Update: Managed to fix it by installing flatpak. With the latest distrobox, there is no error when distrobox-host-exec fails. With the older versions 1.5.X, it gave an error which led me to know I needed to install flatpak. Maybe it's better to have this error so people don't encounter the same problem. For now, all is well.

**Comment by 89luca89** [comment]
Hi @cmspam yes host-spawn and by proxy, distrobox-host-exec, depend on host's having `flatpak-helper` dbus service to work

Right now I cannot know when this is not working, because the absence of the service results in a `127` error code, which is the same as `command not found`

Not sure, maybe @1player knows something more about this :+1: 

But I'd say this is something to discuss in `host-spawn` repo, not here

**Comment by voyaah-rs** [comment]
We ran into this since docker was being called using host-spawn by out tech team with distrobox managing dev envs. No errors were reported, but docker commands simply wouldn't return a response. Installing flatpak on the host OS fixed it. Maybe declare a dependency to flatpak when installing distrobox?

(Currently on Endeavour OS - Arch - Gnome 46 - Wayland. Kernel 6.9)

**Comment by 1player** [comment]
I might look into printing an error if host-spawn is unable to contact Flatpak over DBus

**Comment by fearlessgeekmedia** [comment]
I'm having the same problem, but my host is Void Linux (musl). And I actually do have flatpak installed on it.

**Comment by 1player** [comment]
Does `flatpak-spawn --host` work for you from inside the container? If yes, it might be a host-spawn bug, if not, you might want to file a bug with the flatpak project.

**Comment by fearlessgeekmedia** [comment]
Doesn't work.

Can't find bus: Cannot spawn a message bus without a machine-id: Unable to load /var/lib/dbus/machine-id or /etc/machine-id: Failed to open file “/var/lib/dbus/machine-id”: No such file or directory.

I don't see where Flatpak doesn't support musl, and Void Linux has Flatpak in their musl repos. If Flatpak doesn't support musl, then I would think Void shouldn't have it in their musl repos.

**Comment by fearlessgeekmedia** [comment]
OK. Looks like if I do `dbus-launch distrobox enter [containername]` everything works.

**Comment by 1player** [comment]
Sounds like dbus isn't correctly configured on your host / by your login system. Not a distrobox nor host-spawn bug.

**Comment by fearlessgeekmedia** [comment]
Right. I figured that after I figured out what fixed the problem. I need to see what's going on with my dbus. I have seemed to have problems ever since I switched to sddm. Lightdm was giving me issues after some time. But it's not a problem. For now, I've got a workaround with an alias in my .bashrc and my .zshrc.
