### ISSUE TITLE
[Discussion] Provide migration path for existing exports due to login changes

### ISSUE THREAD

**Issue by pavinjosdev** [89luca89/distrobox#1207]
This is related to PR #1069  and the way it changes how we enter distrobox, using `su` as opposed to the older `bash -l`.
This breaks existing exports of bins/apps.
Users must be provided a migration path to update their existing exports without breakage on upgrading to the next major version of distrobox.

[Example](https://github.com/89luca89/distrobox/commit/3b1e312f884cad2185c3b57dcde470a5d7914c61#commitcomment-138299620) of early adopter having issue. 🥺
Created at the [request](https://github.com/89luca89/distrobox/commit/3b1e312f884cad2185c3b57dcde470a5d7914c61#commitcomment-138672065) of Luca. 🚀

**Comment by 89luca89** [comment]
Since commit https://github.com/89luca89/distrobox/commit/6e26cb2a304e38b0eb0f3f7d0e8d2476ae511e84 we have `distrobox-export --list-apps` and `distrobox-export --list-binaries`

So now, we can do this to re-export apps and binaries from a container:

`distrobox-export --list-binaries | tr -d " " | awk -F"|" '{print "distrobox-export --bin "$1 " --export-path $(dirname "$2")"}' | sh -`

`distrobox-export --list-apps | cut -d' ' -f1 | xargs -I{} distrobox-export --app {}`

**Comment by 89luca89** [comment]
Release done, warning done :+1:
