### ISSUE TITLE
vscode gnome key ring

### ISSUE THREAD

**Issue by vorticalbox** [89luca89/distrobox#1258]
I don't believe this is an issue with distrobox but it may be. 

When i login into GitHub to use copilot, it fails to add to the gnome key-ring so i have to login in every time i start vscode from a box. 

is there a solution for this? i have searched around but i cannot find much help

host: pop!_os
box image: docker.io/node:latest

```You're running in a GNOME environment but the OS keyring is not available for encryption. Ensure you have gnome-keyring or another libsecret compatible implementation installed and running.```

**Comment by m2Giles** [comment]
This can be fixed by changing a setting in the argv.json.

If you follow the help page it links to a workaround that lists how to fix inside of a flatpak. But the key and value should be "password-store": "gnome-libsecret"

Which should then pick up the libsecret compatible service you have running. Despite the name it should grab gnome keyring or kwallet.

If you don't have either of those running on your host, this workaround won't work.
