### ISSUE TITLE
shell prompt no longer differentiates when inside container

### ISSUE THREAD

**Issue by camckay** [89luca89/distrobox#1369]
**Describe the bug**
I assume this is related to [d626559 ](https://github.com/89luca89/distrobox/commit/d626559baaa4e6ccb35b3bb0befc9d46b7aa837e)

Now when entering a container there is no longer any change to the shell prompt, making it impossible to tell when you are actually in a container. 

**To Reproduce**
Simply upgrade to 1.7.2. Issue occurred both in Arch (distro package) and Debian (download).

**Expected behavior**
Some sort of visual indication at the prompt that you are in a container and, preferably, which container. Previously it changed the host name to the container name. Now it simply shows the exact same prompt as the host.

**Desktop (please complete the following information):**
 - podman 
 - Which version or podman, docker or lilipod? 4.3.1 and 5.0.2
 - Which version of distrobox? 1.7.2
 - Which host distribution? Debian and Arch
 - How did you install distrobox? distro package (Arch) and download from github/manual install (Debian)

**Comment by 89luca89** [comment]
Yes this is now the new behaviour

If you don't have cutom-prompts, then it will be like:

![image](https://github.com/89luca89/distrobox/assets/598882/c30fa44c-e42d-498d-8be8-7b569cb33753)


If you use a custom prompt, you need to use $CONTAINER_ID instead of `\h` or $HOSTNAME
this is retro-compatible with containers created previously
