### ISSUE TITLE
[Suggestion] create: default to "Y" instead of "N"

### ISSUE THREAD

**Issue by misobarisic** [89luca89/distrobox#139]
Imagine this scenario. You type this command in:

```bash
distrobox create fedora-rawhide --image registry.fedoraproject.org/fedora:rawhide
```

You explicitly provided the image name yet you don't have it installed. In this scenario, `distrobox-create` defaults to `NO` if you just press enter. My suggestion is to default to `YES` since the user's intent would be to use that image even in the case it might have slipped their mind when it comes to previously downloading the image.

**Comment by 89luca89** [comment]
I'm not much in agree with this, there are already two way of doing `y` by default by using:

`distrobox create fedora-rawhide --image  --image registry.fedoraproject.org/fedora:rawhide --non-interactive`
`DBX_NON_INTERACTIVE=1 distrobox create fedora-rawhide --image  --image registry.fedoraproject.org/fedora:rawhide`

Also this is consistent with a lot of package managers that default to y/N instead of Y/n

As of this maybe it's better to change the flag from `--non-interactive/-N` to `--yes/-y` which is similar to how other pkg manager handles this

**Comment by SigmaSquadron** [comment]
> Also this is consistent with a lot of package managers that default to y/N instead of Y/n

Flatpak is a package manager that uses Y/n by default.

**Comment by 89luca89** [comment]
> > Also this is consistent with a lot of package managers that default to y/N instead of Y/n
> 
> Flatpak is a package manager that uses Y/n by default.

I said a lot not all 😜 

Anyway it's just my gripe of starting a potentially big download I tend to prefer no to yes

**Comment by misobarisic** [comment]
> > Also this is consistent with a lot of package managers that default to y/N instead of Y/n
> 
> Flatpak is a package manager that uses Y/n by default.

If I am not mistaken, Luca's a Fedora user and `dnf` defaults to `y/N`.

For example, both `apt` and `pacman` default to `Y/n`.

**Comment by misobarisic** [comment]
> Anyway it's just my gripe of starting a potentially big download I tend to prefer no to yes

Understandable

**Comment by 89luca89** [comment]
Ahaha yes

Anyway it's not a big problem for me 
It does not break compatibility with otherndistrobox versions, so if anyone wants to do a PR for this it's OK for me
