### ISSUE TITLE
[Discussion] unityhub / xdg-open

### ISSUE THREAD

**Issue by Xdavius** [89luca89/distrobox#1466]
Hi sir.

I'm trying to use unityhub inside a distrobox. Howerver, it needs to open a web browser to login. I have tried lot of method without success. Is it an issue from distrobox ? does I missed something ? I also have installed firefox btw.

The same issue is reproductible with all apps that uses external browser.

Idea and help will be appreciated.

reguards

**Comment by Xdavius** [comment]
Found this too : 
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/xdg-open;

without results.

**Comment by Xdavius** [comment]
found ! installing all xdg* does the job... need to find the one that do the tricks.

init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/xdg-open; <--- this is not needed

regards, closing

**Comment by adrianbienias** [comment]
It's not working for me.

`sudo apt install --reinstall xdg-utils` reinstalls packages successfully,
but after running `unityhub`, links/buttons in the Unity Hub window (to sign in or create new account) don't work,
so ultimately it's the same issue as before reinstalling `xdg-utils`

I'm trying to make `xdg-open https://unity.com` work, because it doesn't in distrobox container but does work fine on host.

Any ideas?
