### ISSUE TITLE
[Error] Entering Distrobox Fedora 35 fails

### ISSUE THREAD

**Issue by dermariusz** [89luca89/distrobox#156]
**Describe the bug**
Distrobox fails during the creation of a user within the container.

**To Reproduce**
`distrobox create fedora-35 --image registry.fedoraproject.org/fedora-toolbox:35`
`distrobox enter --name fedora-35`

**Logs**
[docker.log](https://github.com/89luca89/distrobox/files/7967027/docker.log)

**Desktop**
 - OS: openSUSE
 - Version: 15.4

**Comment by 89luca89** [comment]
Hi @dermariusz 
Yes I can reproduce the problem, seems like the user is present "somewhere" in the system, so useradd fails, but still it's not "really" present so passwd fails...

Checking what is going on :+1:

**Comment by 89luca89** [comment]
@dermariusz seems like the problem was that on OpenSUSE the `nscd` socket was mounted, creating problems with user management inside the container.

Pushed a commit to fix this here: https://github.com/89luca89/distrobox/commit/6186c105654f07179fbf5e942c32cac99b2b3c62

I checked on Leap and TW where it was failing and works now, can you check if it also fixes for you?

**Comment by dermariusz** [comment]
It works. Thank you.
