### ISSUE TITLE
[Discussion] Specify which container manager to use when both docker and podman are installed

### ISSUE THREAD

**Issue by stemcc** [89luca89/distrobox#193]
**Is your feature request related to a problem? Please describe.**
It's not clear how to select which container manager to use during container creation / init / enter if the host has both podman and docker installed

**Describe the solution you'd like**
A command line switch or environment variable to select the container manager distrobox should use.

**Additional context**
Unless I've missed it in the documentation, it doesn't seem possible to manually choose podman or docker. I'm on Fedora 35.

**Comment by misobarisic** [comment]
@89luca89 is this another reason for implementing a config file of some sort? A switch like this needs to be persistent. Otherwise every command would, for example, require `-d/--docket` to be present.

On the other hand, by using an explicit container manager flag only with `distrobox-create`, then trying both a `distrobox-enter` using `podman` and `docker` would be needed. Would also apply to all other commands.

**Comment by 89luca89** [comment]
I'm not against this at all, but we need to plan this out :smile: 

I'd say we could do with:

- a flag `--container-manager/-cm` and specify id (podman/docker, podman default)
- a env variable: `DBX_CONTAINER_MANAGER` so that it can be simply set in an rc file

After this we can think about some sort of config file (~/.config/distrobox/distrobox.conf? we should respect XDG here) and the config file just be a set of env variables that we source

for now env variables can be used for various functionalities as explained in the man pages here:

- https://github.com/89luca89/distrobox/blob/main/docs/usage/distrobox-create.md
- https://github.com/89luca89/distrobox/blob/main/docs/usage/distrobox-enter.md

**Comment by 89luca89** [comment]
#207 solved this
