### ISSUE TITLE
[Error] Failed to connect to bus even though i used the --init command

### ISSUE THREAD

**Issue by SViN24** [89luca89/distrobox#245]
**Describe the bug**
according to the following example i should have access to an init system

https://github.com/89luca89/distrobox/blob/main/docs/useful_tips.md#using-init-system-inside-a-distrobox

but i do not 

**To Reproduce**
run what i run in the picture

**Expected behavior**
i should have access to systemctl as the example shows and also be able to enable that service

**Logs**
[distroboxverbose.txt](https://github.com/89luca89/distrobox/files/8571170/distroboxverbose.txt)
[podmanlog.txt](https://github.com/89luca89/distrobox/files/8571173/podmanlog.txt)

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Version : 22.04LTS

**Additional context**
podman version 3.4.4

**Comment by SViN24** [comment]
accidentally had a wrong image in my clip board history but lets ignore that...

**Comment by 89luca89** [comment]
Hi @SViN24 

Can you try with latest `main` branch version 1.2.15?

I tried just now on an alma 8-init image and it works as expected, I can install openssh, set it to an higher port (because rootless podman cannot access ports <1024) and enabled it successfully

![image](https://user-images.githubusercontent.com/598882/165503913-e1730bbc-7fc2-4f76-a977-3eae6a1f9e98.png)

**Comment by SViN24** [comment]
yes it seems to work perfectly when running from the main branch. i can even call other systemd commands like localectl

**Comment by 89luca89** [comment]
Perfect, closing this, hope to finalize the release soon :smile:
