### ISSUE TITLE
[Suggestion] Improve shell detection

### ISSUE THREAD

**Issue by 89luca89** [89luca89/distrobox#247]
Right now shell detection is based on the $SHELL variable

This works generally except for `/bin/ash` which is not a standalone package, but is provided by `busybox`

Let's try and find a way to install the desired SHELL without resorting to hardcoding anything

**Comment by nathanchance** [comment]
Isn't this really only a problem for `ash`? Every other shell that I can think of is a standalone package with the shell's name on most distributions; for example, Arch Linux has [a whole wiki page](https://wiki.archlinux.org/title/Command-line_shell) on shells and it seems like all of them are the name of the shell from what I can tell.

Perhaps there could be a helper function like `get_shell_package` so that `ash` can be mapped to `busybox`, along with any other weird ones that might come up?

**Comment by 89luca89** [comment]
I imagine is just for `ash`, I'd like to keep it as simple as possible, so it could even be a single `if ash then busybox` thing if it's an isolated case
Else we could resort to the pkg managers builtin search to do stuff, but I doubt that every one out there has a `provides` command like dnf for example

**Comment by 89luca89** [comment]
In the end I just inserted a quirk for it, not worth wasting too much time on it

**Comment by PureTryOut** [comment]
Does this now run `busybox`? That won't work, it'll need to be `busybox sh`.

**Comment by 89luca89** [comment]
> Does this now run `busybox`? That won't work, it'll need to be `busybox sh`.

Nono, it just sets the package name to install to busybox
It leaves the shell to ash
