### ISSUE TITLE
[Error] /usr/bin/distrobox-enter: eval: line 352: syntax error near unexpected token `;'

### ISSUE THREAD

**Issue by AdamIsrael** [89luca89/distrobox#268]
**Describe the bug**

Attempting to run `distrobox-enter` results in a syntax error

**To Reproduce**

`distrobox-enter -n fedora-toolbox-36`
`distrobox-enter`

**Expected behavior**

Distrobox should enter the container.

**Logs**
[distrobox-error.log](https://github.com/89luca89/distrobox/files/8687061/distrobox-error.log)
[podman.log](https://github.com/89luca89/distrobox/files/8687067/podman.log)

**Desktop (please complete the following information):**
 - OS: Fedora Silverblue
 - Version 36

**Additional context**

Running distrobox 1.2.15 installed via RPM

**Comment by 89luca89** [comment]
Hi @AdamIsrael can you check if latest git version shows the same error?
Thanks

**Comment by 89luca89** [comment]
NVM @AdamIsrael I can reproduce this

It is because the container does not have some stuff in the environment, next commit will fix this

Now what I think about it, it shouldn't happen that you do not have these variables declared inside the container creation, are you sure you're starting a `distrobox` container, and not a `toolbx` container?

I ask because the default name (`fedora-toolbox-35`) is the same for both!

**Comment by AdamIsrael** [comment]
Hi @89luca89. You're right; I had created `fedora-toolbox-35` with `toolbx`, not `distrobox`. I deleted the container, recreated it with `distrobox`, and now it works. I hadn't realized that they wouldn't work interchangeably.

Thanks!
