### ISSUE TITLE
[Suggestion] Prefer GUI authentication over sudo for rootful containers

### ISSUE THREAD

**Issue by 1player** [89luca89/distrobox#312]
I prefer my toolbox to use rootful podman so it has full access to the machine and /dev. The podman container is set up to start at boot, and I would like to open a terminal directly into the toolbox.

The problem is that `distrobox enter --root toolbox` uses `sudo` for authentication, so it has to be run from a shell or there's no way for me to enter my admin password.

My suggestion is to prefer the default polkit authentication UI whenever possible (see screenshot), instead of sudo. This can be done by replacing the `sudo` calls in distrobox with `pkexec`.

![image](https://user-images.githubusercontent.com/690120/172346609-43d0f4d3-3c32-433f-b777-daa43ea771ea.png)

**Comment by 89luca89** [comment]
What about making `sudo` configurable?

Instead of sudo we could set up a `distrobox_sudo_program` variable
It will default to sudo
and it will be configurable (via ENV and via config file) to whatever you need, pkexec or doas for example

**Comment by PgBiel** [comment]
With the latest pull request merged, this is now doable! (Docs were updated on this matter.)

Possible solutions (to use a graphical prompt without a shell):
1. Set a system-wide `SUDO_ASKPASS` environment variable, which will cause `sudo` to use the program in the path specified by that variable to authenticate when there is no shell. (Its output to stdout will be used as the password input.) For example, you can write a script in the form: 

```sh
#!/bin/sh
zenity --password "Root authentication required"
```

(replace `zenity` - the GNOME/GTK app - with your preferred graphical prompt program, e.g. `kdialog` for KDE users. Note that you may also install zenity within any desktop environment.)
and save it to e.g. `~/.local/bin/my-password-prompt`, then make it executable (e.g. `chmod +x ~/.local/bin/my-password-prompt`). Afterwards, running `echo 'export SUDO_ASKPASS="~/.local/bin/my-password-prompt"' >> ~/.profile` and then logging out then logging in should be enough to make `sudo` automatically use your newly-created password prompt program for authentication when there is no shell. (This should work even on older, pre-latest PR distrobox versions, by the way.)

2. You may also use the latest PR's feature that allows you to change the sudo program, e.g. by setting `distrobox_sudo_program="some program"` in `~/.distroboxrc` or the like, or `DBX_SUDO_PROGRAM` as an environment variable in your `~/.profile` (or the like).

Setting it to `sudo --askpass` will force sudo to always use the program in the path specified by `SUDO_ASKPASS`, while setting it to `pkexec` (for example) will run `pkexec` instead (which is always a graphical prompt).

It is worth noting that, if you go the `pkexec` route, **make sure you configure persistence,** because distrobox invokes the sudo program multiple times under the hood. So, if persistence is not configured, you will have to type your root password multiple times to manage or enter rootful containers. The advantage of using `sudo` with `SUDO_ASKPASS` is that it has persistence configured by default - but it's also possible to configure that for `pkexec` and other sudo programs.

**Comment by 89luca89** [comment]
Thanks @PgBiel  for the contribution!

**Comment by PgBiel** [comment]
You're welcome!! :handshake:
