### ISSUE TITLE
[Error] Commands generated with distrobox-export do not support whitespace and special characters in arguments

### ISSUE THREAD

**Issue by pgasior** [89luca89/distrobox#439]
**Describe the bug**
Commands generated with `distrobox-export` do not pass arguments with whitespaces or special characters to containers properly.
This also happens with `.desktop` files generated by distrobox.

**To Reproduce**
I wrote simple python script that prints received arguments
```python
#!/usr/bin/env python

import sys

print(f'Received {len(sys.argv)}:')
for i, arg in enumerate(sys.argv):
    print(f'{i}: {arg}')
```
Then exported with `distrobox-export --bin`. I tried few inputs, but didn't receive expected results
```
$ pathtest "arg with spaces"
Received 4:
0: /home/deck/dev/path-test/pathtest
1: arg
2: with
3: spaces
```
```
$ pathtest 'special "!@#'
/home/deck/.local/bin/distrobox-enter: eval: line 501: unexpected EOF while looking for matching `"'

An error occurred
```

**Expected behavior**
It works fine when calling binary directly, or calling generated script from inside container
```
dev/path-test/pathtest "arg with spaces"
Received 2:
0: dev/path-test/pathtest
1: arg with spaces
```
```
$ dev/path-test/pathtest 'special "!@#'
Received 2:
0: dev/path-test/pathtest
1: special "!@#
```
```
(deck@steamdeck ~)$ distrobox enter arch
[deck@arch ~]$ pathtest 'special "!@#'
Received 2:
0: /home/deck/dev/path-test/pathtest
1: special "!@#
```

**Desktop (please complete the following information):**
 - Are you using podman or docker? podman
 - Which version or podman or docker? 4.2.1
 - Which version of distrobox? 1.4.1 on SteamDeck

**Additional context**
I tried playing around with various escaping strategies, but couldn't find anything that would cover all cases. This one is probably the closest
```shell
#!/bin/sh
# distrobox_binary
# name: arch
if [ ! -f /run/.containerenv ] && [ ! -f /.dockerenv ]; then
    command="/home/deck/.local/bin/distrobox-enter  -n arch -- \" /home/deck/dev/path-test/pathtest "
    for i in "$@"
    do
        command="$command $(printf "%q " "$i")"
    done
    command="$command \""
    echo $command
    eval "$command"
else
    /home/deck/dev/path-test/pathtest "$@"
fi
```
but it still fails the `pathtest 'special "!@#'` test. Maybe best solution would be to just base64 encode input args and have some program inside container that would decode and exec binary directly, skipping the whole shell escaping mess.

**Comment by 89luca89** [comment]
Nice catch @pgasior  :smile: 

Will work on this

**Comment by pgasior** [comment]
Thanks for working on this! 
It will break if a double-quoted string contains both an escaped double-quote and a single quote.
```
(deck@steamdeck distrobox)$ pathtest "\"'"
/home/deck/dev/distrobox/distrobox-enter  -n arch --  /home/deck/dev/path-test/pathtest    '"''
/home/deck/.local/bin/pathtest: eval: line 15: unexpected EOF while looking for matching `''
/home/deck/.local/bin/pathtest: eval: line 16: syntax error: unexpected end of file

(2)(deck@steamdeck distrobox)$ ~/dev/path-test/pathtest "\"'"
Received 2:
0: /home/deck/dev/path-test/pathtest
1: "'
```

It also still doesn't work for ,desktop files exported with --app. I exported mpv and tried playing a file with spaces in name, but mpv didn't receive the correct filename. When the filename contains special characters it also fails to even start.
This is entry that got generated, and I guess it is missing that custom escaping logic
`Exec=/home/deck/dev/distrobox/distrobox-enter  -n arch -- '  mpv --player-operation-mode=pseudo-gui --  %U'`

**Comment by 89luca89** [comment]
@pgasior  just pushed an update that fixes the double quoting :+1: 

> This is entry that got generated, and I guess it is missing that custom escaping logic
Exec=/home/deck/dev/distrobox/distrobox-enter -n arch -- ' mpv --player-operation-mode=pseudo-gui -- %U'

Yep, I still need to address that, I want first to ensure the logic is done (and it's simpler with bins/commands to test :smile: )

**Comment by 89luca89** [comment]
This command seems to still error out:

> Found a weird case where it can still crash (I think the backslash is escaping the backslash added via sed): ```distrobox-enter -- python -c 'import sys;print(sys.argv)' \\\'\ \"```

**Comment by HugLifeTiZ** [comment]
I noticed this the other day, and thought about making a PR to change the way this is handled, but got swept up in life stuff.

IMO, I think trying to cram stuff into a variable is the wrong approach. I think you should simply use `"$@"` as-is, because it always handles spaces and quoted arguments correctly. It's the only true array that exists in POSIX sh.

In the version I currently have, you have a `container_command` variable, and this bit in argument parsing:

```
-e | --exec | --)
	shift
	container_command=$*
	break
	;;
```

You are currently not using `$*` or `$@` at all anywhere else in your code. So just forget about a dedicated variable for the container command, and use the rest of the remaining arguments as the container command with `"$@"`.

**Comment by HugLifeTiZ** [comment]
Sorry to double-post, but I thought I would try and give this a go myself, and ran head-first into the fact that you are doing a lot of stuff to manipulate/alter `container_command` into `result_command` in the `generate_command` function, and you print out the resulting command to capture it in a variable with command substitution rather than just... keeping the variable assignment. And the only place generate_command gets called is at the very end, gets stuck into a variable, and that variable gets eval'd without any quoting. There's... **a lot** to unpack here.

First of all, `eval` without its argument quoted is destroying whatever quoting you tried to do inside the variable because of word splitting. If you want to have any control over word splitting to `eval`, you *must* quote whatever you're passing to it.

If you're dead-set on creating some sort of variable for holding the command, the more things you do to pass around that variable, the more precarious its contents are. The thing of printing it out with printf to redundantly capture it via command substitution is not helping. POSIX sh does not have any concept of variable scope. `result_command` will survive after the function returns.

So if you **must** do it that way, change it to this:

```
generate_command
eval "${result_command}"
```

Personally, I think the cleanest approach is to manipulate `$@` directly, but it will require much more rethinking of what you're doing because of limitations in how the `$@` array works. First off, you can't do it in a function. Because while variable scope does not exist in POSIX sh, *argument scope* does. Every function has its own `$@`. But you're only calling that function in one place, so you don't need it to be a function.

You can prepend variables to `$@` like so: `set -- "additional front value" "$@"`
And you can append variables to it like so: `set -- "$@" "additional back value"`
You can even do them at the same time with multiple quoted values: `set -- "first" "second" "$@" "penultimate" "last"`

It looks like you're using `result_command` to put together the command for the container manager, so you can still use `result_command` in tandem with this, but since you're manually quoting inside of that variable, you would pass it to `set` bare, like so: `set -- ${result_command} "$@"`

Preservation of quoting is very important. If I find time, I will attempt to make a PR that rewrites all of this messy handling, but please don't count on this because life is pretty hectic for me at the moment.

**Comment by 89luca89** [comment]
@HugLifeTiZ 

Thanks for the PR, I was already developing a solution here also: https://github.com/89luca89/distrobox/pull/448

I'll test your PR with the various edge cases and see if it works better, thanks a lot!

**Comment by 89luca89** [comment]
As of latest commit escaped whitespace are handled correctly
I'll leave this open a little bit more to see if we can find other edge cases for it :+1:

**Comment by 89luca89** [comment]
Latest commit also fixes all the problems with exported graphical applications

**Comment by manan-gup** [comment]
Is there any way to export apps like `mpv` before the next release happens?

**Comment by Meister1593** [comment]
When exporting blender (from arch container, for instance),  and trying to open using it from outside, any whitespace charater will break blender opening that file
because it doesn't quote file paths
before (can't open file):
![image](https://user-images.githubusercontent.com/7141787/229289322-ee15ecd8-42d1-4f7f-8cca-b0ad9a55e3f7.png)
after (can open file):
![image](https://user-images.githubusercontent.com/7141787/229289338-f614360a-6708-4131-8f1f-bfeb8d0472dc.png)


should issue be created for this?
