### ISSUE TITLE
Toolbox derivative?

### ISSUE THREAD

**Issue by bam80** [89luca89/distrobox#46]
Hi, just thinking shouldn't the two projects be merged together?
https://github.com/containers/toolbox/issues/197#issuecomment-1000358229

**Comment by 89luca89** [comment]
Hi @bam80 
Well as stated, this project takes inspiration from toolbx itself 😄 

If the underlying tech is the same (containers) distrobox is a bit more leaning towards compatibility. This implies some things

1- the choice of using POSIX shell so that we do not have problems of either glibc versions or presents at all (compatibility with musl systems)
2- the choice of supporting plain OCI images instead of having to maintain dedicated ones implies that the `distrobox-init` or `entrypoint` has to do a lot more work to create a useable environment, that means that the 1st `distrobox-enter` can be quite slow, as it's installing, which leads to point 3
3- using plain OCI images meansnthat some of them are REALLY minimal. To maintain a broader compatibility distrobox installs only the bare minimum to work (sudo, psproc, utils-linux, shadow). A toolbx dedicsted image has a lot more components by default. 
4- it wants to supports multiple container managers, so for now podman and docker, in future I would like to support nerdctl for example


From what I see from the toolbx project (which I was using extensively before) has different principles driving it, more of a "seamless" transition between host and toolbx, so that all the same default packages are present, distrobox version is the same and so on. 

So I don't know if the two projects can merge easily

**Comment by bam80** [comment]
Thanks. Still, I don't see much contradictions here, considering Distrobox supports fedora OCI also, the OS Toolbox represents by default. So it should be nearly the same user experience after all..
I see the points of each project, I just don't see the point to maintain them both in parallel, instead of one merged project..

**Comment by 89luca89** [comment]
> considering Distrobox supports fedora OCI also, the OS Toolbox represents by default. So it should be nearly the same user experience after all..

Yes it supports the toolbox images because they are a superset of plain oci images
Still for those the experience is overlapping yes
The difference is in the plain images here

> I see the points of each project, I just don't see the point to maintain them both in parallel, instead of one merged project..

Different POVs on a similar argument 
I started distrobox really because of this, and seeing the issues on toolbx their target is clear

**Comment by alcir** [comment]
@bam80 your thinking is to a certain extent like asking why KDE and GNOME could not get merged. :sweat_smile:  Krita and GIMP? Why there are two commands doing the same thing, like `less` and `more`? (Ok ok, I don't want to start a discussion about the differences and specific purposes :smile:)
I think that this is the power of Free Software. People can collaborate, cooperation is important. But people is free to develop more tools catering their specific needs and point of views.

**Comment by bam80** [comment]
> I think that this is the power of Free Software. 

It's a power until it's not weakens itself. I can't say about this particular case because I simply don't know, thus is the question.

**Comment by 89luca89** [comment]
Closing the issue, not much is going on here, if in the future there will be other questions and suggestions, we can either reopen it or open a new one
