### ISSUE TITLE
Accessing USB Audio Interface in Distrobox

### ISSUE THREAD

**Issue by drachehavoc** [89luca89/distrobox#483]
I really like a program called Carla Plugin Host, made by Filipe Coelho aka @falkTX, this program allows the use of audio plugins called VSTs (and several other formats), with VSTs it is possible to simulate various instruments and guitar pedal effects, by the way, I'm a Fedora user and I've never used the full power of Carla, as this software lets you run Windows VSTs through Wine, but for that you need a plugin (carla-bridge-win) and there are no binaries for Fedora, and Flatpak version doesn't have access to winelib and mingw compiler during compile time (https://github.com/flathub/studio.kx.carla/issues/8).

Long story short, I was wondering if it was possible to use a Debian Distrobox to properly install wine, calra and carla-bridge-win and use it in Fedora, so I tried, but when I start Carla via Debian Distrobox, Carla appears to have no access to my USB audio interface, see screenshots below:

This is carla running Debian Distrobox:
![image](https://user-images.githubusercontent.com/1902294/196585244-b7a1b991-5fa2-4aba-953f-75e9e90f7a13.png)

This is Carla running on my host
![image](https://user-images.githubusercontent.com/1902294/196585356-4f1f7e39-c578-4083-a4b8-f18229a76493.png)

My text may have gotten a little confusing, I'm not a native american speaker, but I hope someone with a good heart can understand my situation and help.

Thanks

**Comment by 89luca89** [comment]
Hi @drachehavoc 

Does the USB device appear in `lsusb`?
By default all `/dev` is shared between host and guest, so usb should be automatically detected
Does this peripheral need some special driver?

**Comment by znmeb** [comment]
Carla documentation is virtually non-existent. I am doing audio from Distrobox Debian `trixie` containers on a Bluefin host but haven't tried any DAWs in the containers because there are Flatpaks for many of them that run in the host. If you want to look at some working code, it's currently in a branch at https://github.com/AlgoCompSynth/ChucK-in-the-Box/tree/chugl-testing.

This will get merged and there will be documentation in a week or so; the container hosting install scripts for non-Bluefin hosts are done and the container works, so the open issues are mostly documentation and testing. https://github.com/AlgoCompSynth/ChucK-in-the-Box/issues
