### ISSUE TITLE
[Discussion] Link to github.com/toolbx-images/images as a source for prepared distro images

### ISSUE THREAD

**Issue by travier** [89luca89/distrobox#544]
> Is your feature request related to a problem? Please describe.

We're making "toolbox ready" container images for common Linux distributions available in https://github.com/toolbx-images/images.

If I correctly understood the note in https://github.com/89luca89/distrobox/blob/main/docs/compatibility.md#containers-distros, those images should work well with distrobox too, but I have not tested that yet.

> Describe the solution you'd like

Would you be open to mentioning this project in your documentation?

Feel free to let us know what's missing from those images for distrobox.

Thanks!

**Comment by travier** [comment]
I've tried it and some packages still need to be installed apparently:

```
$ distrobox-create --image quay.io/toolbx-images/centos-toolbox:stream9
$ distrobox enter centos-toolbox-stream9
📦❯ sudo dnf history
ID     | Command line                                                     | Date and time    | Action(s)      | Altered
-----------------------------------------------------------------------------------------------------------------------
    10 | upgrade -y                                                       | 2022-12-02 19:29 | Upgrade        |   12 EE
     9 | install -y mesa-dri-drivers mesa-vulkan-drivers vulkan           | 2022-12-02 19:23 | Install        |   12   
     8 | install -y --allowerasing zsh bc curl diffutils dnf-plugins-core | 2022-12-02 19:23 | E, I           |    4   
     7 | install -y zsh                                                   | 2022-12-02 19:23 | Install        |    1   
     6 | -y upgrade                                                       | 2022-11-28 02:40 | Upgrade        |    2   
```

So it works but not fully "faster"/ready.

**Comment by 89luca89** [comment]
Hi @travier I'm extremely glad for this! :smile: 

I think distrobox checks some packages more than Toolbx, doing a quick test I see:

quay.io/toolbx-images/almalinux-toolbox:*
quay.io/toolbx-images/centos-toolbox:*
quay.io/toolbx-images/rhel-toolbox:*
quay.io/toolbx-images/rockylinux-toolbox:*

- curl
- pinentry
- mesa-dri-drivers
- mesa-vulkan-drivers
- vulkan-loader

quay.io/toolbx-images/alpine-toolbox:3.16:
quay.io/toolbx-images/ubuntu-toolbox:

**Comment by 89luca89** [comment]
Hi @travier I'm extremely glad for this! :smile: 

As you noted, the images are already compatible with distobox, they are still doing the "install packages" because I think distrobox add some packages more than Toolbx, doing a quick test I see:

---

quay.io/toolbx-images/almalinux-toolbox:*
quay.io/toolbx-images/centos-toolbox:*
quay.io/toolbx-images/rhel-toolbox:*
quay.io/toolbx-images/rockylinux-toolbox:*

- curl
- pinentry
- mesa-dri-drivers
- mesa-vulkan-drivers
- vulkan-loader

---

quay.io/toolbx-images/alpine-toolbox:3.16:

- vte3

And generally doing

```
		apk add \
			$(apk search -q mesa-dri) \
			$(apk search -q mesa-vulkan) \
			vulkan-loader
```


---

quay.io/toolbx-images/ubuntu-toolbox:*

- bc 
- libvte-2.91-common 
- libvte-common
- libegl1-mesa
- libgl1-mesa-glx
- libvulkan1
- mesa-vulkan-drivers

---

quay.io/toolbx-images/opensuse-toolbox:tumbleweed

- libvte-2*
- Mesa-dri
- libvulkan1
- libvulkan_intel
- libvulkan_radeon

---

quay.io/toolbx-images/debian-toolbox:*

- curl 
- dialog 
- gnupg2 
- bc 
- libvte-2.91-common 
- libvte-common
- libegl1-mesa
- libgl1-mesa-glx
- libvulkan1
- mesa-vulkan-drivers

---

quay.io/toolbx-images/archlinux-toolbox:latest

- bc
- mesa
- opengl-driver
- vulkan-intel
- vulkan-radeon

**Comment by 89luca89** [comment]
If you're interested, I can provide the PRs to add the packages to the various `extra-packages` files,
let me know if it's of interest, and if in case, you prefer all-in-one PR, or a PR for each image

Thanks!

**Comment by travier** [comment]
So overall, it looks like we are mainly missing the vulkan & mesa libs. Any idea why we don't have those in toolbox already?

For all the others, feel free to make a PR directly and we'll pull them in. One commit for each distro would be nice and one PR in total is fine

**Comment by 89luca89** [comment]
Cool for the others, the same stands, let me know if it's ok and if it is, how you'd like the contribution to be split :+1:

**Comment by travier** [comment]
Overall, it looks like we need everything. So let's add everything! 🙂

**Comment by travier** [comment]
Not sure how distrobox does things regarding packages but it might be able to skip the package installation phase if it finds everything it needs directly. That would skip the repo fetch step and thus considerably speed up the first setup step.

**Comment by 89luca89** [comment]
Yep that would make the creation/enter time, the same as normal toolbox, as no package management would be needed :+1: 

Do you prefer if I do a PR for each image, or do one for everything?

**Comment by 89luca89** [comment]
@travier I've added the images in the docs :+1:  sorry but I wasn't able to do a PR on the main project to add the missing "distrobox-only" packages, but $day_job is quite demanding of time lately :joy:
