### ISSUE TITLE
[Error]  Symlinked directories to mounted drives broken inside containers

### ISSUE THREAD

**Issue by ShrirajHegde** [89luca89/distrobox#549]
**Describe the bug**
A symlinked directory is shown in red by `ls` and fails to `cd` into. Trying to enter container while at the symlinked directory gives the error : 
```
Error: crun: chdir `/path/to/symlink(destination)`: No such file or directory: OCI runtime attempted to invoke a command that was not found
```

But doing a `cd` into `readlink -f /path/to/dir` and then using distrobox enter works fine. The problem seems to be that the mount point is mounted at /run/host/dir_name, whereas my other drive is mounted at /dir_name, which makes the symlink inside the container invalid.

**To Reproduce**
Mount a drive to /dir_name
Symlink /dir_name/path/to/dir to somewhere in /home/user/dir (Downloads in my case).
Enter a container from /home/user, try cd into dir
Error: `cd: no such file or directory: dir`
or,
Be on dir and enter a container,
Error: `Error: crun: chdir /home/user/dir: No such file or directory: OCI runtime attempted to invoke a command that was not found`

**Expected behavior**
Mount points in the same relative location from root to preserve symlinks

**Logs**
Logs are too long, but I will provide them if required, I guess I have provided the source of the issue.

**Desktop (please complete the following information):**
 -  Using podman
 - podman version 4.3.1
 - distrobox: 1.4.1

**Comment by 89luca89** [comment]
Hi @ShrirajHegde 

This is an unsupported use case

Root's file system is mounted to `/run/host`, so that's where you'll find your drive
If you want you can use a `--init-hooks` during `create` to add your mountpoints like

`distrobox create -i image:tag -n distroname --init-hooks "mkdir /dest && mount --bind /run/host/dest /dest"`

This can't be done generally by distrobox as it's impossible to just guess by me :sweat_smile: 

If you use standard paths for mountpoints (/mnt/ or /run/media, or /media) it is indeed done automatically

**Comment by ShrirajHegde** [comment]
Hello @89luca89,

Thanks for the reply. I understand.

 I will migrate the mount point to a standard mount location.

**Comment by elyashivhazan** [comment]
@89luca89 doing the method you mentioned above make the mount point useless as the permissions is to the nobody user.
Is #600 the same as this issue #549?
