### ISSUE TITLE
try running `distrobox-enter --root --root <name>`

### ISSUE THREAD

**Issue by trueFireblade** [89luca89/distrobox#572]
I don't know how you managed it but erm great software:

$ sudo distrobox-enter --root oracle
Running distrobox-enter as sudo is not supported.
 try instead running:
        distrobox-enter --root --root oracle
$ sudo distrobox-enter --root --root oracle
Running distrobox-enter as sudo is not supported.
 try instead running:
        distrobox-enter --root --root --root oracle

[Great software working as intended](https://user-images.githubusercontent.com/49287879/209725129-0687b612-9248-42f7-9bd0-62ce74a4f101.png)

**Comment by juhp** [comment]
That's a rather disparaging bug report :-/

This is a volunteer opensource project, made by people contributing their own free time.

**Comment by trueFireblade** [comment]
It is just that I would assume for software that heavily uses docker to be tested equally thoroughly when run as root user and I admitedly was quite annoyed by this behaviour yesterday. Though I would appreciate it if someone were to fix it, as I'm certain I'm not the only person who has docker setup in a way that only root user can access it. (Plus: Probably should fix the message to say "running X as root is not supported", as it seems the root user is the issue, not sudo(which just means you run a command under a different user and that different user happens to be root user unless specified otherwise))

**Comment by misobarisic** [comment]
Yes. The error message is wonky but the command you are provided with is correct. It never said `try running "sudo distrobox-enter --root --root"`.   

Getting caught up in meaningless semantics is not going to get us anywhere. And if they bother you too much, just open a PR solving the problem.

**Comment by 89luca89** [comment]
While I really appreciate when a bug is found (because fixing it is beneficial for everyone), I will not tolerate mocking the work of me, and many other people, done in our free time, that your are consuming **for free**.

So, either open a bug report that follows the rules, without being sassy and mocking the work that **you are using for free and done in our free time**, or open a PR and fix it yourself, using **your free time**.

I will close this as I don't consider this a valid report, nor a valid way to interact with the project and community.

I invite you to be more considerate and respectful of other people's work, as this is not helpful and doing this very reply is only wasting my and other contributors' time, which is precious.

Being part of an open source community
