### ISSUE TITLE
mounting permission denied for vboxusb devices because of other group ?

### ISSUE THREAD

**Issue by uinguzero** [89luca89/distrobox#622]
I want to use distrobox on my opensuse tumbleweed, but it always gives me an error when i run distrobox als my normal user on the following

`error mounting "/dev/vboxusb/003/002" to rootfs at "/dev/vboxusb/003/002"`
i've looked at the owner of these files and it is not my normal user but

```
crw-rw---- 1 root vboxusers 189, 257 Feb 13 10:25 002
crw-rw---- 1 root vboxusers 189, 258 Feb 13 10:25 003
crw-rw---- 1 root vboxusers 189, 259 Feb 13 10:25 004
```
How can i make distrobox either skip mounting these files, or how do i give distrobox permission to these files....

opensuse tumbleweed
podman version  
Client:       Podman Engine
Version:      4.3.1
API Version:  4.3.1
Go Version:   go1.17.13
Built:        Tue Jan 17 01:00:00 2023
OS/Arch:      linux/amd64

**Comment by 89luca89** [comment]
Hi @uinguzero 
you need to add your host's user to the vboxusers group (maybe issue a reboot after that)
Also if you're using podman, make sure you're using `crun` as runtime, instead of `runc` as the last one does not support to retain the user host's group into the container

I'll link you this useful read about it: https://www.redhat.com/sysadmin/supplemental-groups-podman-containers

I'm closing this as it's not a distrobox bug, but feel free to join the matrix/telegram channel for more help (or simply reply here :+1: )
