### ISSUE TITLE
[Suggestion] Make distrobox-host-exec use the host's environment variables

### ISSUE THREAD

**Issue by PoQuatre** [89luca89/distrobox#632]
**Is your feature request related to a problem? Please describe.**
I'm trying to execute a script on the host through `distrobox-host-exec`, but it seems that the HOME variable is the one set in the container instead of the host.
I confirmed this using this command `distrobox-host-exec echo $HOME` which returns `/path/to/container/home` instead of `/path/to/real/home`.

**Describe the solution you'd like**
I would love to have a `--host-env` flag (or any other name) that discards all environment variables set in the container and only takes the host's environment variables.

**Describe alternatives you've considered**
The solution that I'm using right now is manually setting the HOME variable before executing `distrobox-host-exec` and resetting it afterwards, here is a small example doing this:
```bash
#!/bin/bash

OLD_HOME=$HOME # Set OLD_HOME to `/path/to/container/home`
HOME=/path/to/real/home

distrobox-host-exec echo $HOME # Should return `/path/to/real/home`

HOME=$OLD_HOME # Reset HOME to `/path/to/container/home`
```

**Comment by misobarisic** [comment]
This happens because $HOME gets substituted prior to _escaping out of the container_. 

Host home is available through `DISTROBOX_HOST_HOME` environment variable inside the container.
If you want to query any arbitrary host environment variable while executing it outside the container, you can run `distrobox-host-exec printenv ENV_VAR_NAME` instead

**Comment by 89luca89** [comment]
:thinking: it would make sense to swap those host/guest vars before execution tho,
will try to think about a fix :+1:

**Comment by 89luca89** [comment]
Reflecting on this the problem here is

`distrobox-host-exec echo $HOME` will resolve $HOME **before** executing the command on the host
That's why

If you do ` distrobox-host-exec sh -c "echo \$HOME"`
it actually will print the home of the host, which is correct

**Comment by andrea-berling** [comment]
Hello 👋  I ran into a different issue that would also be solved by the possibility to specify env-vars to keep for `distrobox-host-exec` (like the underlying `host-spawn` allows anyway): `distrobox-host-exec` seems to load the value for the `PATH` environment variable from somewhere that is not the current value of the `PATH` variable inside the container:
![Image](https://github.com/user-attachments/assets/d2f232d3-a5d1-4495-bf6f-4d928a533706)
Currently, I'm using `distrobox-host-exec` to spawn a terminal emulator I installed in my Arch Linux distrobox container. Unfortunately, that terminal emulator does not have access the `PATH` I usually expect it to, and thus can not see find some of the binaries that I would like to use.
It's probably a minor change to add support for this, since `host-spawn` basically allows for it already:
![Image](https://github.com/user-attachments/assets/ad559246-038d-4e40-8646-34eab5077582)
Do you foresee any issues with this @89luca89? Should I bother making a PR?
