### ISSUE TITLE
[Discussion] Add instructions on how to setup NVIDIA GPU/AMD support

### ISSUE THREAD

**Issue by nonetrix** [89luca89/distrobox#633]
Is your feature request related to a problem? Please describe.
It is hard to find documentation or any guide of how to get NVIDIA GPU support to work in distrobox, the only time I've gotten it to work is in Vanilla OS which seems to already have it setup. I've only been able to get it to work with software rendering in NixOS

Describe the solution you'd like
Instructions to set NVIDIA support on distrobox in the readme at least for Ubuntu, also AMD setup guide might be good too but I imagine it's not as difficult

Describe alternatives you've considered
Non any I can think of

Additional context

See that it is using software rendering
![image](https://user-images.githubusercontent.com/45698918/219906748-e4949d3f-a4ec-437e-b5ac-c5de522cd75b.png)

Currently what I have done to get software rendering working at least is to
1. Install docker
2. Install distrobox
3. Install xhost
4. Install nvidia-docker (I don't know if this is needed tbh) 
5. Run xhost +
6. Install nvidia drivers in distrobox

**Comment by nonetrix** [comment]
Please add something like this to FAQ for NVIDIA users on NixOS
https://www.reddit.com/r/NixOS/comments/pe1zkj/miniguide_nvidia_gpu_acceleration_in_docker/

**Comment by 89luca89** [comment]
Closing this as now nvidia support is built-in

**Comment by pfcouto** [comment]
Hello @89luca89. My machine (a laptop) is running Fedora 37 and I have a RTX 3080 laptop. I want to install a SDK, however, I am getting several errors when trying to install it, since the script is made for Ubuntu, for that reason I wanted to try a solution using ditrobox. However, my project uses machine learning (that's what the 3080 is for) and for that reason the Distrobox with Ubuntu should be able to access my 3080 and CUDA to use it in machine learning. How can I do this? DO I have to do something special? Thanks!
