### ISSUE TITLE
[Suggestion] Ability to unset environment variables before entering or executing distrobox commands

### ISSUE THREAD

**Issue by fredizzimo** [89luca89/distrobox#656]
**Is your feature request related to a problem? Please describe.**
When I set a custom home directory, many environment variables gets set with the wrong default values pointing to the old home directory. Most notably the  `XDG_` variables, but more criticially the `ZDOTDIR`. When `ZDOTDIR` is defined `.zshenv` won't be sourced and therefore distrobox will use my regular configuration instead of my intended distrobox specific one.

The `PATH` variable, and other variables also contains references to the old `$HOME`, which can cause binaries to be read from the wrong place.

**Describe the solution you'd like**
I would like a way to zero out certain environment variables, configured by the `create` command. For the path, and similar list variables, it would be nice to be able to filter out certain elements,.  Or even clear it completely to use the distribution default, but that's  perhaps less usesful, since then it also filters out any paths given by the commandline on the fly.

**Describe alternatives you've considered**
Perhaps an even better solution, or at least more flexible would be some `pre_enter` script, that is only run when the distrobox is entered, but not when subshells are spawned inside it. Then I could do all unsetting and filtering myself.

The regular rc files are not good for this, unless there's a way to determine if the shell was spawned from the outside or not, in that case I could zero the variables out myself and in the case of `ZDOTDIR` being wrong, call the correct one.

**Comment by luc14n0** [comment]
This raises the same concerns as #420

**Comment by fredizzimo** [comment]
The workaround I have been using is to add the following patch to `distrobox-enter`

```diff
diff --git a/distrobox-enter b/distrobox-enter
index 997fd14..5b8b1e1 100755
--- a/distrobox-enter
+++ b/distrobox-enter
@@ -386,7 +386,8 @@ generate_command() {
        result_command="${result_command} ${container_name}"
 
        if [ -n "${container_command}" ]; then
-               result_command="${result_command} ${container_command}"
+                quoted_container_command="\\\"${container_command}\\\""
+               result_command="${result_command} sh -c \"\\\$(getent passwd ${USER} | cut -f 7 -d :) -lc ${quoted_con
tainer_command}\""
        else
                # if no command was specified, let's execute a command that will find
                # and run the default shell for the user

```

That enusres that the distrobox is always entered through the login shell, and then I can unset and set whatever I want in my rc file.  And I can now use a completely different set of xdg dirs, to properly isolate the distrobox configuration and caches, but still otherwise share the home directory.

I also had to do the following patch, but I'm not sure exactly why, so I haven't created an issue. But I think it was because it tried to run the host docker with a non-existing path. 

```diff
diff --git a/distrobox-enter b/distrobox-enter
index 5b8b1e1..277eff3 100755
--- a/distrobox-enter
+++ b/distrobox-enter
@@ -310,9 +310,9 @@ generate_command() {
        # pass distrobox-enter path, it will be used in the distrobox-export tool.
        if [ "${skip_workdir}" -eq 0 ]; then
                workdir="$(echo "${PWD:-${container_home:-"/"}}" | sed -e 's/"/\\\"/g')"
-               if [ -n "${workdir##*"${container_home}"*}" ]; then
-                       workdir="/run/host${workdir}"
-               fi
+               #if [ -n "${workdir##*"${container_home}"*}" ]; then
+               #       workdir="/run/host${workdir}"
+               #fi
        else
                # Skipping workdir we just enter $HOME of the container.
                workdir="${container_home}"
```

**Comment by fredizzimo** [comment]
Also note that this issue is more generic than https://github.com/89luca89/distrobox/issues/420

In my configuration, in addition to setting the XDG directories, 
1. I remove a few things from the path so it doesn't pick up some binaries from my host home dir
2. Unset the PIP_CACHE_DIR
3. Unset PIPENV_VENV_IN_PROJECT
4. Set some environment variables specific to the distrobox
5. Unset some environment variables related to Direnv
6. Unset some environment variables related to NVIM

So the system needs to be quite flexible, I defintiely think it should support custom shell scripting, and not just a few extra parameters. In my case I use distrobox for reproducible developement environment running including compilers, python, docker (which runs on the host) and so on.  And it runs Ubuntu, while I'm running Arch Linux. So it needs to be quite isolated from the rest of the system, but not too isolated.

I'm using direnv to forward all the relevant commands to distrobox when I'm working on one of those projects.

**Comment by luc14n0** [comment]
You're use case seems to need the right amount of isolation indeed. And I believe that even I would benefit from such a feature myself. By the way, I also agree with **distrobox** always starting a login shell, even when commands are being passed directly to the `distrobox` script(s) through the CLI to be run inside the container.

From where I stand, we could benefit from having two things:

1. Having an option flag to pass specific variables to unset environment variables as the user deems necessary.
2. And I believe that having an option flag to clear the environment would be useful too. By "clearing the environment" I mean not inherit basically all the environment from the host as is being done currently:
``` sh
	# Loop through all the environment vars
	# and export them to the container.
	set +o xtrace
	# disable logging for this snippet, or it will be too talkative.
	for i in $(printenv | grep '=' | grep -Ev ' |"|`|\$' |
		grep -Ev '^(HOST|HOSTNAME|HOME|LANG|LC_CTYPE|PATH|SHELL|XDG_.*_DIRS|^_)'); do
		# We filter the environment so that we do not have strange variables,
		# multiline or containing spaces.
		# We also NEED to ignore the HOME variable, as this is set at create time
		# and needs to stay that way to use custom home dirs.
		result_command="${result_command} --env \"${i}\""
	done
```

I can't say right now exactly how much useful the second thing is as the interaction we currently have is a bit complex, at least for me at the moment. However, it makes me wonder whether the current model (seen in the code excerpt above) is really needed, because I believe that important variables that should be passed along to the container by **distrobox** are the ones defined in the user's shell RC files, which in turn are already being sourced when the shell is launched. If I'm right, in theory we are just cluttering the container's environment.

I'm going to start some experiments and let's see whether something useful comes out of them.

**Comment by cs96and** [comment]
+1 for this feature.  I've been using `env` to workaround it for now, e.g...

```
env -u ENVVAR_TO_REMOVE -u ANOTHER_ENVVAR_TO_REMOVE distrobox-enter -n my-distroboxname
```

you can you use this to add environment variables too, rather than using `--additional-flags "--env BLAH=1"`, you could do...

```
env -u ENVVAR_TO_REMOVE -u ANOTHER_ENVVAR_TO_REMOVE BLAH=1 distrobox-enter -n my-distroboxname
```

**Comment by motorto** [comment]
is there currently a away to purge al host envs when entering the container ?

**Comment by cs96and** [comment]
You can use `env -i` to completely clear the environment, e.g...

`env -i BLAH=1 distrobox-enter -n my-distroboxname`

**Comment by sandorex** [comment]
I have problems with PATH preferring host cargo .local/bin and other paths than the ones inside the container

`env -u PATH - distrobox ..` does not work for me

**Comment by cs96and** [comment]
> `env -u PATH - distrobox ..` does not work for me

You have an extra dash there.  According to the `env --help` that will completely clear then environment, which may be causing other issues for you.

```
$ env --help
<snip>
A mere - implies -i.  If no COMMAND, print the resulting environment.
```

Does `env -u PATH distrobox ..` work?

**Comment by sandorex** [comment]
Ah i did not see that, thanks!

Full working command: `env -u PATH $(which distrobox) enter`

**Comment by mrdev023** [comment]
I use NixOS and when i work on KDE (dev). I use `env -i bash -l` to completely reset bash env vars.

I need made that because i had conflict with libs, qml, binaries.

And then, i need load required vars like XDG_RUNTIME_DIR DBUS_SESSION_BUS_ADDRESS
And run `source "$HOME/kde/build/plasma-mobile/prefix.sh"`

**Comment by 89luca89** [comment]
Indeed I'd like to keep dbox lean on flags, use `env -u` if you want to exclude env variables

**Comment by jcrben** [comment]
I worked up this script (w/ a little help from copilot):

```
# Usage: bash unset_env_and_enter_distrobox.sh my-distrobox

ALL_VARS=( $(env | cut -d= -f1) )

ESSENTIALS=(
    XDG_DATA_HOME
)

VARS_TO_UNSET=()
for var in "${ALL_VARS[@]}"; do
    skip_var=false
    for essential in "${ESSENTIALS[@]}"; do
        if [[ "$var" == "$essential" ]]; then
            skip_var=true
            break
        fi
    done
    if ! $skip_var; then
        VARS_TO_UNSET+=("$var")
    fi
done

UNSET_ARGS=()
for var in "${VARS_TO_UNSET[@]}"; do
    if [[ -n "$var" ]]; then
        UNSET_ARGS+=("-u" "$var")
    fi
done

env "${UNSET_ARGS[@]}" distrobox enter --clean-path "$@"
```

I found that the only variable I needed to leave in is `XDG_DATA_HOME` otherwise it can't find the distrobox and prompts to create it.

**Comment by authorizedaccess** [comment]
I tested it myself and found that we only need this single line to have cleanest possible state for environment in the containers:

```sh
env -i $(which distrobox) enter --clean-path <container-name>
```

@jcrben You had issues because when env is cleared, it can't find the distrobox at all and gives error. It does not specifically require `XDG_DATA_HOME`. Can you try the above command and check if everything works? 
I did check/analyze the whole distrobox scripts/code with LLM to be sure. It also come to same conclusion that anything the distrobox needs, it has fallbacks in the scripts of distrobox itself and does not need HOST env.

For ease of use, I use an alias in my rc file for the enter command like this:

```sh
alias dbxe="env -i $(which distrobox) enter --clean-path"
```

I can then easily use `dbxe <container-name>`.
