### ISSUE TITLE
[Suggestion] Program got installed in Distrobox AND host

### ISSUE THREAD

**Issue by aheadoftrends** [89luca89/distrobox#677]
So I created a distrobox to try some ai stuff. Installing Miniconda3 through their official shell script downloaded from https://docs.conda.io/en/latest/miniconda.html after running it whithout sudo and installing it somewhere in ~. It seems running succesfully. But the Terminal on the host changed immidiately (showing a "(base)" in front of the username.  What did happen here. On my host I try to only use package managers and this is not what I am trying to achieve

What might have caused this?

**Comment by 89luca89** [comment]
As clearly stated in the docs and README, Distrobox *shares the home with the host*, so if you install stuff in the home, you'll obviously also find it on the host

You can use a custom home for distrobox, you can take a look at the docs on how it works

**Comment by aheadoftrends** [comment]
> As clearly stated in the docs and README, Distrobox *shares the home with the host*, so if you install stuff in the home, you'll obviously also find it on the host
> 
> You can use a custom home for distrobox, you can take a look at the docs on how it works

Thanks for the fast reply. The surprising thing to me was that the program was also imidiatly running on the host without using the same init system.

But this might not be if I close the distrobox, I am going to try that

**Comment by weatherhead99** [comment]
this is likely because miniconda installs some lines in ~/.bashrc (or your equivalent) which initializes the miniconda environment when a new shell starts. Since your host distro and the distrobox distro share your home directory, they also share any .bashrc initialization code. Miniconda is relatively standalone, and it's no surprise to me that it is able to work on both host and distrobox client

**Comment by 89luca89** [comment]
Yes the solution to this is using custom homes
