### ISSUE TITLE
[Discussion] Distrobox overrides certain security settings in the container that I want to set differently

### ISSUE THREAD

**Issue by VorpalBlade** [89luca89/distrobox#685]
## Is your feature request related to a problem? Please describe.
Whenever I start the container (e.g. after a reboot of the host), distrobox seems to run it's setup script. This is at least true on the Arch image that I'm using.

Some or most of the settings it changes most likely make sense, but there are certain things it overrides that I strongly disagree with:

* Empty password for root and my user
* No password needed for sudo.

Is there a way I can make it skip changing these things every time?

## Describe the solution you'd like
A documented way to disable these overwrites

## Describe alternatives you've considered
My own script that undoes the things distrobox just did? I guess?

**Comment by abuturaaab** [comment]
I can confirm the same behavior on Ubuntu and Fedora containers.

**Comment by luc14n0** [comment]
Hi there folks,

Let me put the missing piece on the table so you can see what's going on, and you should be able to see why this is not a real concern.

In a rootless **Distrobox** container, the **root** user has the same level of privileges as your normal user in the host system. So if your user in the host system has sane privileges, whatever you do inside the container shouldn't be a real threat for the host system, hypothetically speaking.

**Distrobox** is a facility meant to tightly integrate its containers with the host system and provide a smooth experience. With this regard and keeping in mind what has been said previously, it only makes sense to _not_ have passwords for **root** and normal users and password-less `sudo`, since the super user **root** actually doesn't have special powers like the one in the host system.

Therefore you shouldn't be in the need to look for ways to avoid this behavior.

**Comment by VorpalBlade** [comment]
> Therefore you shouldn't be in the need to look for ways to avoid this behavior.

Isn't there still a difference in privilege between root and normal user in the frame of the container though? Neither is privileged on the host. But they still map to different UIDs within the namespace, right?

**Comment by luc14n0** [comment]
Yes, yes, there is a difference in privileges between both and they map to different _UID_'s just like a regular system.

Rootless containers are installed somewhere under our home directories (`~/.local/share/containers/` by default, in systems without customization that affect this location). So, basically a regular user inside a container will have restricted access to locations inside said container, while the `root` user will practically have unlimited access, just like a regular system.

**Comment by 89luca89** [comment]
As explained you shouldn't really worry about the passwordless sudo inside a rootless container, it really is always your user's capability anyway

What you can do, is run passwd after the first setup, and remove the passwordless sudo file and you should be good to go

**Comment by VorpalBlade** [comment]
> As explained you shouldn't really worry about the passwordless sudo inside a rootless container, it really is always your user's capability anyway
> 
> What you can do, is run passwd after the first setup, and remove the passwordless sudo file and you should be good to go

I tried that, but for the Arch Linux container at least, it reset it on every container startup (e.g. after reboot of the host).

**Comment by 89luca89** [comment]
You can use `--init-hook` during container creation to run custom commands after the initialization, but before entering
this way they'll always be run even after restarts
