### ISSUE TITLE
VMclass isn't respected by gnome DE

### ISSUE THREAD

**Issue by MiMillieuh** [89luca89/distrobox#728]
**Describe the bug**
When running a program with a desktop export (exemple distrobox-export code) the program won't launch in the same icon as the shortcut like if it can't find it's WMclass. however the WMclass is the same for the entry and the program.

**To Reproduce**
Export an app from a container on gnome wayland and run it with the shortcut or cli in the container

**Expected behavior**
An app pinned on my dock should launch in the same icon not in a separated one that I can't pin or do anything with it.

**Desktop (please complete the following information):**
 - Are you using podman or docker? podman
 - Which version or podman or docker? podman-4.5.0-1.fc38.x86_64
 - Which version of distrobox? 1.4.2.1 (please make an update cause the Nvidia thing would be so cool and it's mentioned in the doc but still not upstream since five month...)

**Additional context**
Tried on multiple container (arch, alma, opensuse, fedora)

**Comment by luc14n0** [comment]
Hi there MiMillieuh,

From one user to another, what you want is just not possible with the current design, and it's actually more of a feature than a bug. **distrobox** is a CLI application, so it depends on a Terminal emulator in order to be run (`Terminal=true`). Different desktop files - with different names - can't bear the same WM Class, I'm afraid. That's "regulated" by **Freedesktop**'s desktop entry specs, and IMHO that's how it's supposed to be.

Let's take another example somewhere else, **NeoVim**. **NeoVim** has two packages in **openSUSE**, one (`neovim`, CLI) has a desktop file which will open it in the "default" Terminal emulator; and another package (`neovim-gtk`, "GUI") that has a desktop file which will open a GUI of its own - well, it's basically a modified **GNOME** Terminal, like a fork -, but most importantly, that allow its desktop file to have a `Terminal=false` entry. Thus, it can group windows together, in the fashion you're expecting **distrobox** to do.

**NeoVim**'s CLI:

![image](https://github.com/89luca89/distrobox/assets/31497094/161a05ba-b528-449a-9bf0-d9c839f0d3d7)

After opening it, **Console** (new **GNOME**'s default Terminal emulator) pops up:
![image](https://github.com/89luca89/distrobox/assets/31497094/4665c9cd-6990-4111-b853-8d4d1693cb6f)

Now, with **NeovimGtk** things are different:

![image](https://github.com/89luca89/distrobox/assets/31497094/9b4a3b40-6cff-46d6-86ab-34d7ea83f6d1)

If we open `foo.txt`, we have:

![image](https://github.com/89luca89/distrobox/assets/31497094/6a421689-1f20-4b46-bd72-6f64daac4c5c)

And if we open a new window with `bar.txt`:

![image](https://github.com/89luca89/distrobox/assets/31497094/1e28e72f-4055-4cd3-900b-17b31f29d1ac)

They get grouped under the same WM Class/dash icon!

But the way **distrobox** makes use of desktop files for exported apps or created containers is more convenient and easier than either tinkering with a "GUI" or "replacing" the default Terminal emulator desktop file with a modified one that would allow it to group created containers/exported apps all together. But quite less convenient, and trickier, generally speaking.

**Comment by MiMillieuh** [comment]
Thanks for your clear explanation. I understand now but it would be a nice feature though.

**Comment by luc14n0** [comment]
Yeah, no problem.

> Different desktop files - with different names - can't bear the same WM Class, I'm afraid. That's "regulated" by Freedesktop's desktop entry specs, and IMHO that's how it's supposed to be.

I have to amend what I said there. WM Class is not "regulated" by **Freedesktop**'s desktop entry spec. Actually, the one which sets the class name is the application itself, and if the application developer/author exposed a proper CLI option - usually `--class` -, we can set a class name with its help:

```
$ gnome-terminal --help-all | grep class
  --class=CLASS                   Program class as used by the window manager

$ alacritty --help | grep class
        --class <general> | <general>,<instance>
            Defines window class/app_id on X11/Wayland [default: Alacritty]
```

So, I made a little experiment to see if we could try to "isolate" **distrobox** in its own WM class, so it doesn't get mixed with "normal" terminal. I tested both **GNOME Terminal** and **Alacritty**. **GNOME Terminal** seems to have a bug and doesn't really create the class name we pass through `--class` - I remember hitting this issue long time ago. However, **Alacritty** respected it:

![image](https://github.com/89luca89/distrobox/assets/31497094/08919341-1354-464a-9cf5-6c77545c7146)

I could open a request adding something to the docs with my findings, but this feature will be limited to the terminal in use, thus I don't think **distrobox** should switch to use it, despite this being the only practical way we may have to use such a feature - the other one, as I already said, where **distrobox** would develop its own GUI, the way I see it the chances of that happening are quite slim (at least for now).

Too much fuss for not much reward.

It's my belief that this is not mentioned anywhere simply because not many know about the Desktop Entry spec.

**Comment by luc14n0** [comment]
> And the fact that it's not mentioned anywhere makes it sounds like a bug.

Here I beg to differ. Just because a behavior is not mentioned somewhere it doesn't make it sound like a bug. Not everyone will know the gory details about this or that, and **distrobox** has quite some documentation around already.

**Comment by Lady-vamp** [comment]
I'm experiencing the same issue where the web browser app displays two icons every time I open it. It's quite annoying. Have you guys found a solution to make the WM class work properly?

**Comment by luc14n0** [comment]
The solution - if we really can call it that way - I've found is limited to the terminal being able to let users to pass a custom value as the window class name.

**GNOME Terminal** is bugged, it won't set the name even though it has an option too - and since it's dead upstream, I don't think is even worth reporting this. **GNOME**'s **Console** is not as flexible as **Terminal** and don't have an option to set the window class nome. Personally I haven't tried other terminal looking for this option, though. Only **Alacritty** worked out setting the window class name.

That said, if someone is willing to use the method I've found, it would be an involved process until automation is achieved (if that ever happens, at all).
