### ISSUE TITLE
[Error] Boxes created in verbose mode can't run graphical applications.

### ISSUE THREAD

**Issue by na-sa-do** [89luca89/distrobox#757]
**Describe the bug**
A box created with `-v` set will not be able to run graphical applications.

**To Reproduce**
1. `distrobox create -v -n test`
2. `distrobox enter test` (NO `-v`)
3. run any graphical application (I tried Geany and KWrite, representing GTK and Qt)

**Expected behavior**
It runs.

**Logs**
https://drive.google.com/file/d/1RLMj8f0pWKac0KY7FqUkV0by19ZUXgyj/view

**Desktop (please complete the following information):**
- podman 4.5.0
- distrobox 1.4.2.1

**Additional context**
KWin 5.27.5 in XWayland mode.

**Comment by luc14n0** [comment]
Hi there,

I'm afraid this issue you're facing has nothing to do with **distrobox**. I tried it myself also using **openSUSE Tumbleweed** host/guest and **Geany** opens here, under both **Wayland** and **X11**.

Looking at the logs you provided, the interesting part is at the bottom of them:

``` sh
~> geany
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Geany: cannot open display

~> kwrite
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.
```

Have you tried to install them in the host system? Does `echo $XDG_SESSION_TYPE` show `wayland`? Does `printenv | grep DISPLAY` show you both `DISPLAY` and `WAYLAND_DISPLAY`, what are their values?

**Geany** not being able to find the display (through `DISPLAY`/`WAYLAND_DISPLAY`) and **KWrite** screaming 'Could not find the Qt platform plugin "wayland" in ""' and 'Could not load the Qt platform plugin "xcb" in "" even though it was found.' - note the empty values there -, points to something missing/wrong with the environment **distrobox** was invoked. Are you by any chance using **FISH** shell?

**Comment by na-sa-do** [comment]
Yes, Geany and KWrite both launch fine in the host. Critically, they also launch fine from a box that wasn't created in verbose mode. `$DISPLAY` is `:0`, `$WAYLAND_DISPLAY` is `wayland-0`, and `$XDG_SESSION_TYPE` is `wayland` in all three cases. I'm just using bash.

**Comment by luc14n0** [comment]
Huh, interesting! They seem to be in order.

All that the verbose mode is doing is to pass `set -o xtrace` to the shell so we can see what's going on in the script during its execution; and pass `--log-level debug` to Podman/Docker, that's it.

I feel like this is one of those rare moments that whatever happens inside the container, during its creation, something gets messed up somehow. Alas, I'm gonna clean up the logs you provided, as they are full off color escape codes and non-printable characters that affects their reading - and we should implement a way for **distrobox** to provide a "clean" log, or disable colors for the verbose mode. Once cleaned, I'm gonna review it.

By the way, have you tried to create a new container to see if the issue is reproducible in your system?

**Comment by 89luca89** [comment]
This is not reproducible, please if this occurs again comment here with the new findings
