### ISSUE TITLE
[Discussion] Restore services export

### ISSUE THREAD

**Issue by joefiorini** [89luca89/distrobox#772]
The ability to export services from a distrobox was recently removed. I had been using this feature for appimagelauncher. The reason for removing this feature is that we have `—init` and therefore don’t need to export services.

I still don’t have (nor do I want) systemd in my container, so I can’t start the service there.  How do we run services that are in a distrobox container now?

**Comment by 89luca89** [comment]
Hi @joefiorini 

I've removed it because it was a burden to maintain, rarely worked as expected, and most of the usecases are better covered by `--init`

In your case I suggest to export the bin and do a user systemd unit

Hopefully in the future I'll have time/will to fix the export, but for now this is out of my priorities
