### ISSUE TITLE
[Bug] distrobox still has issues with tzdata on debian based distros

### ISSUE THREAD

**Issue by rrahl0** [89luca89/distrobox#820]
**Describe the bug**
in some shape of form updating/installing the package tzdata breaks the container to a point where only recreating it makes it usable again. For some reason, mounting /etc/localtime from the HOST doesn't work.

**To Reproduce**
create container (for example docker.io/ubuntu:23.04) and install a package which requires tzdata (vim-athena).

**Expected behavior**
it should work and update without issues.

**Logs**
output of podman logs: https://paste.opensuse.org/pastes/da28086954e5

**Desktop (please complete the following information):**
 - Are you using podman or docker? podman
 - Which version or podman or docker? 4.5.1
 - Which version of distrobox? 1.5.0.2 or git

**Additional context**
at least on debian you can lock the package (as it's installed and should satisfy most package installs) and use most of the stuff. but it could still be a bother when a package depends on the newer version.

Edit: here is `ls -l /etc/localtime`:
```
$ ls -l /etc/localtime 
lrwxrwxrwx 1 root root 33 Jun 24 11:58 /etc/localtime -> /usr/share/zoneinfo/Europe/Berlin
```

**Comment by KeithIMyers** [comment]
If it helps, the error in the terminal is 

mount: /etc/localtime: mount point does not exist.
E: Problem executing scripts DPkg::Post-Invoke 'if [ -e /run/host//etc/localtime ] || [ -e /run/host/$(readlink -fm /run/host//etc/localtime) ]; then mount --rbind $(readlink -fm /run/host//etc/localtime) /etc/localtime 2>/dev/null || mount --rbind /run/host/$(readlink -fm /run/host//etc/localtime) /etc/localtime; fi'
E: Sub-process returned an error code

**Comment by h4kon** [comment]
Happens to me too. 
It is worth exposing that  Kinoite and Silverblue it happened when I create a container with ubuntu 23.04 it does not configure the user. This only occurs when I enter the created container.

**Comment by wusaby-rush** [comment]
I have also this problem with debian 

unable to install new version of '/usr/share/zoneinfo/Etc/UTC': Device or resou
rce busy

**Comment by RHOPKINS13** [comment]
I'm having this issue as well. I'm running Distrobox with Podman rootless on a Steam Deck.

From the deck:
`(deck@RHOPKINS13-SteamDeck ~)$ ls -l /etc/localtime
lrwxrwxrwx 1 root root 38 Jan 18  2022 /etc/localtime -> ../usr/share/zoneinfo/America/New_York
(deck@RHOPKINS13-SteamDeck ~)$ ls /usr/share/zoneinfo
Africa      Atlantic   Chile    Eire     Factory  GMT-0      Iceland      Jamaica            Libya    Navajo   Portugal    right      Turkey     UTC           Zulu
America     Australia  CST6CDT  EST      GB       GMT0       Indian       Japan              MET      NZ       posix       ROC        tzdata.zi  WET
Antarctica  Brazil     Cuba     EST5EDT  GB-Eire  Greenwich  Iran         Kwajalein          Mexico   NZ-CHAT  posixrules  ROK        UCT        W-SU
Arctic      Canada     EET      Etc      GMT      Hongkong   iso3166.tab  leapseconds        MST      Pacific  PRC         SECURITY   Universal  zone1970.tab
Asia        CET        Egypt    Europe   GMT+0    HST        Israel       leap-seconds.list  MST7MDT  Poland   PST8PDT     Singapore  US         zone.tab
`
But from within the distrobox (Ubuntu 22.10):
`(deck@ubuntu ~)$ ls -l /etc/localtime
lrwxrwxrwx 1 root root 30 Jul  3 22:03 /etc/localtime -> /usr/share/zoneinfo/US/Eastern
(deck@ubuntu ~)$ ls -l /usr/share/zoneinfo
total 0
`

The zoneinfo folder is empty / not mounted, and I get all sorts of errors because of it.

**Comment by kekkoudesu** [comment]
I created an Ubuntu container today with `--root`, `--init`, and `--additional-packages "systemd"`. The `/usr/share/zoneinfo` directory was completely empty.

To workaround this, I copied all of the data in my host distribution's `/usr/share/zoneinfo` folder to my home directory, then copied it into my container's `/usr/share/zoneinfo` folder.

It also did not specify a locale, so I needed to edit `/etc/locale.gen` and run `localectl set-locale LANG=en_US.UTF-8` to get Apache to startup.

The only reason I needed to create a container with its own init system in the first place is because Apache—for reasons I still do not know—is not able to `make_sock` for port 443 with the normal SYS_V init system. Will open a separate issue about this. But hey, I finally got what I wanted to work, working!

**Comment by 89luca89** [comment]
I've fixed it with the latest commit
Hopefully forever :joy:

**Comment by kekkoudesu** [comment]
Tested, works great!

**Comment by Gildedter** [comment]
Still having this issue on mint (created using the following command: `SHELL=/bin/zsh distrobox create --name mint --image docker.io/linuxmintd/mint21.1-amd64 --home ~/.containers-home/mint/`)

I have distrobox installed on the steam deck with Steam OS 3.5, the one that comes pre-installed. I'm using a custom home directory because my zsh config (and other configs too) kept polluting the default `/home/deck/` directory, so having several containers installed ends up reading the same config files.

my terminal:
![image](https://github.com/89luca89/distrobox/assets/93777256/d371db9b-024c-40c3-bfcb-ea0c0b3d0d5b)
