### ISSUE TITLE
[Error] Regression for interactive shells

### ISSUE THREAD

**Issue by alexanderfast** [89luca89/distrobox#971]
**Describe the bug**

With the fix for https://github.com/89luca89/distrobox/issues/965 and https://github.com/89luca89/distrobox/issues/963 theres a regression with how interactive shells work.

**To Reproduce**

On commit `7130e2ba7abf7603f7dd66a4c208cd52211e52be` there was the bug of the extra character in newlines, but interactive shell used with enter worked:

```
alex@laptop:~$ distrobox enter debian -- echo foo | hexdump -c     
0000000   f   o   o  \r  \n                                            
0000005
alex@laptop:~$ distrobox enter debian
alex@debian:~$ # <-- second shell inside container
```

Now with `8ee3c50a65ea9b938102c401f0fb9b2d5f07e545` the extra character is fixed, but I can no longer enter a container interactively:

```
alex@laptop:~$ distrobox enter debian -- echo foo | hexdump -c
0000000   f   o   o  \n                                                
0000004
alex@laptop:~$ distrobox enter debian

```

There is never a prompt from inside the container. I can run commands and get their output but the shell no longer behaves as i expect, theres no prompt. Tested with zsh and bash.

**Expected behavior**

Shell should work the same inside and outside the container. Single commands run with enter should not have extra newline characters.

**Comment by akinomyoga** [comment]
This is a simple bug of 785114b7cf2fb57d18ed5ba6dc9d3804cdf12568. The shell function `generate_command` is used as `$(generate_command)`. In this context, stdout (fd 1) is temporarily redirected to a pipe prepared by the shell, so `[ -t 1 ]` cannot be used to test if stdout of the main script is a TTY inside the function `generate_command`.

One way to fix it would be to test the TTY outside `$(...)` and save the result to a shell variable (https://github.com/akinomyoga/distrobox/commit/0cdb61375b49f2f38edf74a5a3d6f74c6d384862):

```diff
diff --git a/distrobox-enter b/distrobox-enter
index e0374eb..3a48fe5 100755
--- a/distrobox-enter
+++ b/distrobox-enter
@@ -300,7 +300,7 @@ generate_command() {
     # To work around this, --headless let's you skip the --tty flag and make it
     # work in tty-less situations.
     # Disable tty also if we're NOT in a tty (test -t 0, test -t 1).
-    if [ "${headless}" -eq 0 ] && [ -t 0 ] && [ -t 1 ]; then
+    if [ "${headless}" -eq 0 ] && [ -n "$_distrobox_use_tty" ]; then
         result_command="${result_command}
             --tty"
     fi
@@ -561,6 +561,11 @@ if [ "${container_status}" != "running" ]; then
 fi

 # Generate the exec command and run it
+if [ -t 0 ] && [ -t 1 ]; then
+    _distrobox_use_tty=1
+else
+    _distrobox_use_tty=
+fi
 cmd="$(generate_command)"
 # shellcheck disable=SC2086
 eval ${cmd}
```

<details><summary>Or, another way is to save the main-script stdout to another file descriptor (for example, fd 11) and test against the saved file descriptor in <code>generate_command</code>.</summary>

https://github.com/akinomyoga/distrobox/commit/c944a72b8650d7c132763c1e82f2d50b54f56227

```diff
diff --git a/distrobox-enter b/distrobox-enter
index e0374eb..f2bad3e 100755
--- a/distrobox-enter
+++ b/distrobox-enter
@@ -300,7 +300,7 @@ generate_command() {
     # To work around this, --headless let's you skip the --tty flag and make it
     # work in tty-less situations.
     # Disable tty also if we're NOT in a tty (test -t 0, test -t 1).
-    if [ "${headless}" -eq 0 ] && [ -t 0 ] && [ -t 1 ]; then
+    if [ "${headless}" -eq 0 ] && [ -t 0 ] && [ -t 11 ]; then
         result_command="${result_command}
             --tty"
     fi
@@ -561,6 +561,7 @@ if [ "${container_status}" != "running" ]; then
 fi

 # Generate the exec command and run it
+exec 11>&1
 cmd="$(generate_command)"
 # shellcheck disable=SC2086
 eval ${cmd}
```
</details>

<details><summary>Or, even another way is to run <code>generate_command</code> without using the command substitution so that <code>generate_command</code> writes the result to the global variable <code>result_command</code>, and to read trhe variable <code>result_command</code> at the caller side.</summary>

https://github.com/akinomyoga/distrobox/commit/39d1ed2c810b638f0974fc532e32cb7589a03531

```diff
diff --git a/distrobox-enter b/distrobox-enter
index e0374eb..07cea78 100755
--- a/distrobox-enter
+++ b/distrobox-enter
@@ -429,16 +429,14 @@ generate_command() {
                result_command="${result_command}
                        sh -c \"\\\$(getent passwd ${USER} | cut -f 7 -d :) -l"\"
        fi
-
-       # Return generated command.
-       printf "%s" "${result_command}"
 }

 container_home="${HOME}"
 container_path="${PATH}"
 # dry run mode, just generate the command and print it. No execution.
 if [ "${dryrun}" -ne 0 ]; then
-       cmd="$(generate_command)"
+       generate_command
+  cmd="$result_command"
        cmd="$(echo "${cmd}" | sed 's/\t//g')"
        printf "%s\n" "${cmd}"
        exit 0
@@ -561,6 +559,7 @@ if [ "${container_status}" != "running" ]; then
 fi

 # Generate the exec command and run it
-cmd="$(generate_command)"
+generate_command
+cmd="$result_command"
 # shellcheck disable=SC2086
 eval ${cmd}
```
</details>

**Comment by 89luca89** [comment]
Thanks again for the investigation! :)
