### ISSUE TITLE
[Error] On NixOS, the /nix directory is still mounted into containers

### ISSUE THREAD

**Issue by A-Lovett** [89luca89/distrobox#978]
Despite [this](https://github.com/89luca89/distrobox/commit/5dd7b00e3f095e1976c0e2aa4f972efdcd6f4f3a) change, multiple people have confirmed they still see the /nix directory mounted into distrobox-created containers. This is after installing distrobox from the current main branch. Thanks.

**Comment by chewblacka** [comment]
I can confirm. `/nix` is still mounted into all containers. Running the latest main branch.

**Comment by 89luca89** [comment]
If that's really needed, then the Nix packager for distrobox can add this to the default config

```conf
container_additional_volumes="/nix:/nix"
```

In one of the supported configuration system paths:

```
	/usr/share/distrobox/distrobox.conf
	/usr/share/defaults/distrobox/distrobox.conf
	/usr/etc/distrobox/distrobox.conf
	/usr/local/share/distrobox/distrobox.conf
	/etc/distrobox/distrobox.conf
```

But this shouldn't be the case
The stuff inside the container should not be inherited by the container
If it is, it's because of ~/.profile or the shell rc file, which should be made then container-aware to add the Nix path only outside of the container

**Comment by 89luca89** [comment]
Also just for headup

If the /nix is still mounted after an update
It's because you'll need to recreate the container for the change to be effective

**Comment by nashamri** [comment]
I can confirm that after the https://github.com/89luca89/distrobox/commit/5dd7b00e3f095e1976c0e2aa4f972efdcd6f4f3a commit I'm getting the same error @chewblacka's getting:
```
 Error: could not start entrypoint.
exec /usr/bin/entrypoint: no such file or directory
```
when using `distrobox` on NixOS.

But is this a distrobox issue or a NixOs packaging issue :thinking: ?

**Comment by 89luca89** [comment]
Thats a duplicate of #315 and a whole other thing

But i'm still not able to resolve that, and it is not a high prio for me now
